<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Repository\ArtifactRepository.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Repository;

use Composer\IO\IOInterface;

class ArtifactRepository extends ArrayRepository implements ConfigurableRepositoryInterface
{
    public function __construct(array $repoConfig, IOInterface $io)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getRepoName()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRepoName');
    }

    public function getRepoConfig()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRepoConfig');
    }

    protected function initialize()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'initialize');
    }
}
