<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Repository\CompositeRepository.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Repository;

use Composer\Package\BasePackage;
use Composer\Package\PackageInterface;

class CompositeRepository implements RepositoryInterface
{
    public function __construct(array $repositories)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getRepoName(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRepoName');
    }

    public function getRepositories(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRepositories');
    }

    public function hasPackage(PackageInterface $package): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'hasPackage');
    }

    public function findPackage($name, $constraint): ?BasePackage
    {
        \ShirabeUnsupportedClass::fail(self::class, 'findPackage');
    }

    public function findPackages($name, $constraint = null): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'findPackages');
    }

    public function loadPackages(array $packageNameMap, array $acceptableStabilities, array $stabilityFlags, array $alreadyLoaded = []): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'loadPackages');
    }

    public function search(string $query, int $mode = 0, ?string $type = null): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'search');
    }

    public function getPackages(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPackages');
    }

    public function getProviders($packageName): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getProviders');
    }

    public function removePackage(PackageInterface $package): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'removePackage');
    }

    public function count(): int
    {
        \ShirabeUnsupportedClass::fail(self::class, 'count');
    }

    public function addRepository(RepositoryInterface $repository): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'addRepository');
    }
}
