<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Repository\ComposerRepository.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Repository;

use Composer\Package\PackageInterface;
use Composer\Config;
use Composer\IO\IOInterface;
use Composer\Util\HttpDownloader;
use Composer\EventDispatcher\EventDispatcher;

class ComposerRepository extends ArrayRepository implements ConfigurableRepositoryInterface, AdvisoryProviderInterface
{
    public function __construct(array $repoConfig, IOInterface $io, Config $config, HttpDownloader $httpDownloader, ?EventDispatcher $eventDispatcher = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getRepoName()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRepoName');
    }

    public function getRepoConfig()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRepoConfig');
    }

    public function findPackage(string $name, $constraint)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'findPackage');
    }

    public function findPackages(string $name, $constraint = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'findPackages');
    }

    public function getPackages()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPackages');
    }

    public function getPackageNames(?string $packageFilter = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPackageNames');
    }

    public function loadPackages(array $packageNameMap, array $acceptableStabilities, array $stabilityFlags, array $alreadyLoaded = [])
    {
        \ShirabeUnsupportedClass::fail(self::class, 'loadPackages');
    }

    public function search(string $query, int $mode = 0, ?string $type = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'search');
    }

    public function hasSecurityAdvisories(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'hasSecurityAdvisories');
    }

    public function getSecurityAdvisories(array $packageConstraintMap, bool $allowPartialAdvisories = false): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getSecurityAdvisories');
    }

    public function getProviders(string $packageName)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getProviders');
    }

    protected function configurePackageTransportOptions(PackageInterface $package): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'configurePackageTransportOptions');
    }

    protected function initialize()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'initialize');
    }

    public function addPackage(PackageInterface $package)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'addPackage');
    }

    protected function loadRootServerFile(?int $rootMaxAge = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'loadRootServerFile');
    }

    protected function fetchFile(string $filename, ?string $cacheKey = null, ?string $sha256 = null, bool $storeLastModifiedTime = false)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'fetchFile');
    }

    protected function lazyProvidersRepoContains(string $name)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'lazyProvidersRepoContains');
    }
}
