<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Repository\FilterRepository.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Repository;

use Composer\Package\PackageInterface;
use Composer\Package\BasePackage;

class FilterRepository implements RepositoryInterface, AdvisoryProviderInterface
{
    public function __construct(RepositoryInterface $repo, array $options)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getRepoName(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRepoName');
    }

    public function getRepository(): RepositoryInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRepository');
    }

    public function hasPackage(PackageInterface $package): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'hasPackage');
    }

    public function findPackage($name, $constraint): ?BasePackage
    {
        \ShirabeUnsupportedClass::fail(self::class, 'findPackage');
    }

    public function findPackages($name, $constraint = null): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'findPackages');
    }

    public function loadPackages(array $packageNameMap, array $acceptableStabilities, array $stabilityFlags, array $alreadyLoaded = []): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'loadPackages');
    }

    public function search(string $query, int $mode = 0, ?string $type = null): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'search');
    }

    public function getPackages(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPackages');
    }

    public function getProviders($packageName): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getProviders');
    }

    public function count(): int
    {
        \ShirabeUnsupportedClass::fail(self::class, 'count');
    }

    public function hasSecurityAdvisories(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'hasSecurityAdvisories');
    }

    public function getSecurityAdvisories(array $packageConstraintMap, bool $allowPartialAdvisories = false): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getSecurityAdvisories');
    }
}
