<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Repository\InstalledRepository.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Repository;

use Composer\Semver\Constraint\ConstraintInterface;

class InstalledRepository extends CompositeRepository
{
    public function __construct()
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function findPackagesWithReplacersAndProviders(string $name, $constraint = null): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'findPackagesWithReplacersAndProviders');
    }

    public function getDependents($needle, ?ConstraintInterface $constraint = null, bool $invert = false, bool $recurse = true, ?array $packagesFound = null): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getDependents');
    }

    public function getRepoName(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRepoName');
    }

    public function addRepository(RepositoryInterface $repository): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'addRepository');
    }
}
