<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Repository\LockArrayRepository.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Repository;

class LockArrayRepository extends ArrayRepository
{
    public function __construct()
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getRepoName(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRepoName');
    }

    public function getCanonicalPackages()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getCanonicalPackages');
    }
}
