<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Repository\PackageRepository.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Repository;

class PackageRepository extends ArrayRepository implements AdvisoryProviderInterface
{
    public function __construct(array $config)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    protected function initialize(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'initialize');
    }

    public function getRepoName(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRepoName');
    }

    public function hasSecurityAdvisories(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'hasSecurityAdvisories');
    }

    public function getSecurityAdvisories(array $packageConstraintMap, bool $allowPartialAdvisories = false): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getSecurityAdvisories');
    }
}
