<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Repository\PathRepository.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Repository;

use Composer\Config;
use Composer\EventDispatcher\EventDispatcher;
use Composer\IO\IOInterface;
use Composer\Util\HttpDownloader;
use Composer\Util\ProcessExecutor;

class PathRepository extends ArrayRepository implements ConfigurableRepositoryInterface
{
    public function __construct(array $repoConfig, IOInterface $io, Config $config, ?HttpDownloader $httpDownloader = null, ?EventDispatcher $dispatcher = null, ?ProcessExecutor $process = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getRepoName(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRepoName');
    }

    public function getRepoConfig(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRepoConfig');
    }

    protected function initialize(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'initialize');
    }
}
