<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Repository\PlatformRepository.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Repository;

use Composer\Package\PackageInterface;
use Composer\Platform\HhvmDetector;
use Composer\Platform\Runtime;

class PlatformRepository extends ArrayRepository
{
    public const PLATFORM_PACKAGE_REGEX = '{^(?:php(?:-64bit|-ipv6|-zts|-debug)?|hhvm|(?:ext|lib)-[a-z0-9](?:[_.-]?[a-z0-9]+)*|composer(?:-(?:plugin|runtime)-api)?)$}iD';

    public function __construct(array $packages = [], array $overrides = [], ?Runtime $runtime = null, ?HhvmDetector $hhvmDetector = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getRepoName(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRepoName');
    }

    public function isPlatformPackageDisabled(string $name): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isPlatformPackageDisabled');
    }

    public function getDisabledPackages(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getDisabledPackages');
    }

    protected function initialize(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'initialize');
    }

    public function addPackage(PackageInterface $package): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'addPackage');
    }

    public static function isPlatformPackage(string $name): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isPlatformPackage');
    }

    public static function getPlatformPhpVersion(): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPlatformPhpVersion');
    }

    public function search(string $query, int $mode = 0, ?string $type = null): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'search');
    }
}
