<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Repository\RepositoryFactory.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Repository;

use Composer\IO\IOInterface;
use Composer\Config;
use Composer\EventDispatcher\EventDispatcher;
use Composer\Util\HttpDownloader;
use Composer\Util\ProcessExecutor;

class RepositoryFactory
{
    public function __construct()
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public static function configFromString(IOInterface $io, Config $config, string $repository, bool $allowFilesystem = false)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'configFromString');
    }

    public static function fromString(IOInterface $io, Config $config, string $repository, bool $allowFilesystem = false, ?RepositoryManager $rm = null): RepositoryInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'fromString');
    }

    public static function createRepo(IOInterface $io, Config $config, array $repoConfig, ?RepositoryManager $rm = null): RepositoryInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createRepo');
    }

    public static function defaultRepos(?IOInterface $io = null, ?Config $config = null, ?RepositoryManager $rm = null): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'defaultRepos');
    }

    public static function manager(IOInterface $io, Config $config, ?HttpDownloader $httpDownloader = null, ?EventDispatcher $eventDispatcher = null, ?ProcessExecutor $process = null): RepositoryManager
    {
        \ShirabeUnsupportedClass::fail(self::class, 'manager');
    }

    public static function defaultReposWithDefaultManager(IOInterface $io): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'defaultReposWithDefaultManager');
    }

    public static function generateRepositoryName($index, array $repo, array $existingRepos): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'generateRepositoryName');
    }
}
