<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Repository\RepositorySet.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Repository;

use Composer\DependencyResolver\PoolOptimizer;
use Composer\DependencyResolver\Pool;
use Composer\DependencyResolver\Request;
use Composer\DependencyResolver\SecurityAdvisoryPoolFilter;
use Composer\EventDispatcher\EventDispatcher;
use Composer\IO\IOInterface;
use Composer\Semver\Constraint\ConstraintInterface;

class RepositorySet
{
    public const ALLOW_UNACCEPTABLE_STABILITIES = 1;
    public const ALLOW_SHADOWED_REPOSITORIES = 2;

    public function __construct(string $minimumStability = 'stable', array $stabilityFlags = [], array $rootAliases = [], array $rootReferences = [], array $rootRequires = [], array $temporaryConstraints = [])
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function allowInstalledRepositories(bool $allow = true): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'allowInstalledRepositories');
    }

    public function getRootRequires(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRootRequires');
    }

    public function getTemporaryConstraints(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getTemporaryConstraints');
    }

    public function addRepository(RepositoryInterface $repo): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'addRepository');
    }

    public function findPackages(string $name, ?ConstraintInterface $constraint = null, int $flags = 0): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'findPackages');
    }

    public function getSecurityAdvisories(array $packageNames, bool $allowPartialAdvisories, bool $ignoreUnreachable = false): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getSecurityAdvisories');
    }

    public function getMatchingSecurityAdvisories(array $packages, bool $allowPartialAdvisories = false, bool $ignoreUnreachable = false): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getMatchingSecurityAdvisories');
    }

    public function getProviders(string $packageName): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getProviders');
    }

    public function isPackageAcceptable(array $names, string $stability): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isPackageAcceptable');
    }

    public function createPool(Request $request, IOInterface $io, ?EventDispatcher $eventDispatcher = null, ?PoolOptimizer $poolOptimizer = null, array $ignoredTypes = [], ?array $allowedTypes = null, ?SecurityAdvisoryPoolFilter $securityAdvisoryPoolFilter = null): Pool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createPool');
    }

    public function createPoolWithAllPackages(): Pool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createPoolWithAllPackages');
    }

    public function createPoolForPackage(string $packageName, ?LockArrayRepository $lockedRepo = null): Pool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createPoolForPackage');
    }

    public function createPoolForPackages(array $packageNames, ?LockArrayRepository $lockedRepo = null): Pool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createPoolForPackages');
    }
}
