<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Repository\VcsRepository.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Repository;

use Composer\Repository\Vcs\VcsDriverInterface;
use Composer\Package\Loader\LoaderInterface;
use Composer\EventDispatcher\EventDispatcher;
use Composer\Util\ProcessExecutor;
use Composer\Util\HttpDownloader;
use Composer\IO\IOInterface;
use Composer\Config;

class VcsRepository extends ArrayRepository implements ConfigurableRepositoryInterface
{
    public function __construct(array $repoConfig, IOInterface $io, Config $config, HttpDownloader $httpDownloader, ?EventDispatcher $dispatcher = null, ?ProcessExecutor $process = null, ?array $drivers = null, ?VersionCacheInterface $versionCache = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getRepoName()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRepoName');
    }

    public function getRepoConfig()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRepoConfig');
    }

    public function setLoader(LoaderInterface $loader): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setLoader');
    }

    public function getDriver(): ?VcsDriverInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getDriver');
    }

    public function hadInvalidBranches(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'hadInvalidBranches');
    }

    public function getEmptyReferences(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getEmptyReferences');
    }

    public function getVersionTransportExceptions(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getVersionTransportExceptions');
    }

    protected function initialize()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'initialize');
    }

    protected function preProcess(VcsDriverInterface $driver, array $data, string $identifier): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'preProcess');
    }
}
