<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Repository\Vcs\GitLabDriver.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.
// Composer\Repository\Vcs\VcsDriver::__construct() is final, so it keeps running the real implementation here.

namespace Composer\Repository\Vcs;

use Composer\Config;
use Composer\IO\IOInterface;
use Composer\Util\HttpDownloader;
use Composer\Util\Http\Response;

class GitLabDriver extends VcsDriver
{
    public const URL_REGEX = '#^(?:(?P<scheme>https?)://(?P<domain>.+?)(?::(?P<port>[0-9]+))?/|git@(?P<domain2>[^:]+):)(?P<parts>.+)/(?P<repo>[^/]+?)(?:\.git|/)?$#';

    public function __construct()
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function initialize(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'initialize');
    }

    public function setHttpDownloader(HttpDownloader $httpDownloader): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setHttpDownloader');
    }

    public function getComposerInformation(string $identifier): ?array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getComposerInformation');
    }

    public function getFileContent(string $file, string $identifier): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getFileContent');
    }

    public function getChangeDate(string $identifier): ?\DateTimeImmutable
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getChangeDate');
    }

    public function getRepositoryUrl(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRepositoryUrl');
    }

    public function getUrl(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getUrl');
    }

    public function getDist(string $identifier): ?array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getDist');
    }

    public function getSource(string $identifier): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getSource');
    }

    public function getRootIdentifier(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRootIdentifier');
    }

    public function getBranches(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getBranches');
    }

    public function getTags(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getTags');
    }

    public function getApiUrl(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getApiUrl');
    }

    protected function getReferences(string $type): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getReferences');
    }

    protected function fetchProject(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'fetchProject');
    }

    protected function attemptCloneFallback(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'attemptCloneFallback');
    }

    protected function generateSshUrl(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'generateSshUrl');
    }

    protected function generatePublicUrl(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'generatePublicUrl');
    }

    protected function setupGitDriver(string $url): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setupGitDriver');
    }

    protected function getContents(string $url, bool $fetchingRepoData = false): Response
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getContents');
    }

    public static function supports(IOInterface $io, Config $config, string $url, bool $deep = false): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'supports');
    }

    public function getRepoData(): ?array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRepoData');
    }

    protected function getNextPage(Response $response): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getNextPage');
    }

    protected function shouldCache(string $identifier): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'shouldCache');
    }

    protected function getBaseComposerInformation(string $identifier): ?array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getBaseComposerInformation');
    }

    public function hasComposerFile(string $identifier): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'hasComposerFile');
    }

    protected function getScheme(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getScheme');
    }

    public function cleanup(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'cleanup');
    }
}
