<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Repository\Vcs\HgDriver.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.
// Composer\Repository\Vcs\VcsDriver::__construct() is final, so it keeps running the real implementation here.

namespace Composer\Repository\Vcs;

use Composer\Config;
use Composer\IO\IOInterface;

class HgDriver extends VcsDriver
{
    public function __construct()
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function initialize(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'initialize');
    }

    public function getRootIdentifier(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRootIdentifier');
    }

    public function getUrl(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getUrl');
    }

    public function getSource(string $identifier): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getSource');
    }

    public function getDist(string $identifier): ?array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getDist');
    }

    public function getFileContent(string $file, string $identifier): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getFileContent');
    }

    public function getChangeDate(string $identifier): ?\DateTimeImmutable
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getChangeDate');
    }

    public function getTags(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getTags');
    }

    public function getBranches(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getBranches');
    }

    public static function supports(IOInterface $io, Config $config, string $url, bool $deep = false): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'supports');
    }

    protected function shouldCache(string $identifier): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'shouldCache');
    }

    public function getComposerInformation(string $identifier): ?array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getComposerInformation');
    }

    protected function getBaseComposerInformation(string $identifier): ?array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getBaseComposerInformation');
    }

    public function hasComposerFile(string $identifier): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'hasComposerFile');
    }

    protected function getScheme(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getScheme');
    }

    protected function getContents(string $url): Response
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getContents');
    }

    public function cleanup(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'cleanup');
    }
}
