<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Filter\PlatformRequirementFilter\IgnoreListPlatformRequirementFilter.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Filter\PlatformRequirementFilter;

use Composer\Semver\Constraint\ConstraintInterface;

final class IgnoreListPlatformRequirementFilter implements PlatformRequirementFilterInterface
{
    public function __construct(array $reqList)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function isIgnored(string $req): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isIgnored');
    }

    public function isUpperBoundIgnored(string $req): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isUpperBoundIgnored');
    }

    public function filterConstraint(string $req, ConstraintInterface $constraint, bool $allowUpperBoundOverride = true): ConstraintInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'filterConstraint');
    }
}
