<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Package\Loader\ArrayLoader.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Package\Loader;

use Composer\Package\BasePackage;
use Composer\Package\Version\VersionParser;

class ArrayLoader implements LoaderInterface
{
    public function __construct(?VersionParser $parser = null, bool $loadOptions = false)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function load(array $config, string $class = 'Composer\Package\CompletePackage'): BasePackage
    {
        \ShirabeUnsupportedClass::fail(self::class, 'load');
    }

    public function loadPackages(array $versions): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'loadPackages');
    }

    public function parseLinks(string $source, string $sourceVersion, string $description, array $links): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'parseLinks');
    }

    public function getBranchAlias(array $config): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getBranchAlias');
    }
}
