<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Package\Loader\RootPackageLoader.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Package\Loader;

use Composer\Package\BasePackage;
use Composer\Config;
use Composer\IO\IOInterface;
use Composer\Package\Version\VersionGuesser;
use Composer\Package\Version\VersionParser;
use Composer\Repository\RepositoryManager;

class RootPackageLoader extends ArrayLoader
{
    public function __construct(RepositoryManager $manager, Config $config, ?VersionParser $parser = null, ?VersionGuesser $versionGuesser = null, ?IOInterface $io = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function load(array $config, string $class = 'Composer\Package\RootPackage', ?string $cwd = null): BasePackage
    {
        \ShirabeUnsupportedClass::fail(self::class, 'load');
    }

    public static function extractStabilityFlags(array $requires, string $minimumStability, array $stabilityFlags): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'extractStabilityFlags');
    }

    public static function extractReferences(array $requires, array $references): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'extractReferences');
    }
}
