<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Package\Loader\ValidatingArrayLoader.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Package\Loader;

use Composer\Package\BasePackage;
use Composer\Package\Version\VersionParser;

class ValidatingArrayLoader implements LoaderInterface
{
    public const CHECK_ALL = 3;
    public const CHECK_UNBOUND_CONSTRAINTS = 1;
    public const CHECK_STRICT_CONSTRAINTS = 2;

    public function __construct(LoaderInterface $loader, bool $strictName = true, ?VersionParser $parser = null, int $flags = 0)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function load(array $config, string $class = 'Composer\Package\CompletePackage'): BasePackage
    {
        \ShirabeUnsupportedClass::fail(self::class, 'load');
    }

    public function getWarnings(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getWarnings');
    }

    public function getErrors(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getErrors');
    }

    public static function hasPackageNamingError(string $name, bool $isLink = false): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'hasPackageNamingError');
    }
}
