<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Proxy stub for Composer\Script\Event: the public surface forwards to the Rust-side entity over RPC.

namespace Composer\Script;

use Composer\Composer;
use Composer\IO\IOInterface;
use Composer\EventDispatcher\Event as BaseEvent;

class Event extends BaseEvent
{
    public function __construct(string $name, Composer $composer, IOInterface $io, bool $devMode = false, array $args = [], array $flags = [])
    {
        [$this->__rhandle, $this->__epoch] = \ShirabeRpcRuntime::callRust(0, '__shirabeConstruct', [static::class, [$name, $composer, $io, $devMode, $args, $flags]]);
        \ShirabeRustObjectRegistry::adopt($this->__rhandle, $this);
    }

    public function getComposer(): Composer
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getComposer', []);
    }

    public function getIO(): IOInterface
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getIO', []);
    }

    public function isDevMode(): bool
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'isDevMode', []);
    }

    public function getOriginatingEvent(): ?BaseEvent
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getOriginatingEvent', []);
    }

    public function setOriginatingEvent(BaseEvent $event): self
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setOriginatingEvent', [$event]);
        return $this;
    }
}
