[package]
name = "shirabe-symfony-console"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A Rust port of symfony/console"
repository.workspace = true
license.workspace = true

[dependencies]
shirabe-pcre.workspace = true
shirabe-php-shim.workspace = true
shirabe-symfony-process.workspace = true
shirabe-symfony-string.workspace = true
anyhow.workspace = true
indexmap.workspace = true
regex.workspace = true

[lints]
workspace = true
