[package]
name = "shirabe-class-map-generator"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A Rust port of composer/class-map-generator"
repository.workspace = true
license.workspace = true

[dependencies]
shirabe-pcre.workspace = true
shirabe-php-shim.workspace = true
shirabe-symfony-finder.workspace = true
anyhow.workspace = true
indexmap.workspace = true

[lints]
workspace = true
