<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Package\Version\VersionSelector.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Package\Version;

use Composer\IO\IOInterface;
use Composer\Package\PackageInterface;
use Composer\Repository\RepositorySet;
use Composer\Repository\PlatformRepository;

class VersionSelector
{
    public function __construct(RepositorySet $repositorySet, ?PlatformRepository $platformRepo = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function findBestCandidate(string $packageName, ?string $targetPackageVersion = null, string $preferredStability = 'stable', $platformRequirementFilter = null, int $repoSetFlags = 0, ?IOInterface $io = null, $showWarnings = true)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'findBestCandidate');
    }

    public function findRecommendedRequireVersion(PackageInterface $package): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'findRecommendedRequireVersion');
    }
}
