<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Package\Version\VersionBumper.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Package\Version;

use Composer\Package\PackageInterface;
use Composer\Semver\Constraint\ConstraintInterface;

class VersionBumper
{
    public function __construct()
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function bumpRequirement(ConstraintInterface $constraint, PackageInterface $package): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'bumpRequirement');
    }
}
