<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Installer\BinaryInstaller.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Installer;

use Composer\IO\IOInterface;
use Composer\Package\PackageInterface;
use Composer\Util\Filesystem;

class BinaryInstaller
{
    public function __construct(IOInterface $io, string $binDir, string $binCompat, ?Filesystem $filesystem = null, ?string $vendorDir = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function installBinaries(PackageInterface $package, string $installPath, bool $warnOnOverwrite = true): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'installBinaries');
    }

    public function removeBinaries(PackageInterface $package): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'removeBinaries');
    }

    public static function determineBinaryCaller(string $bin): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'determineBinaryCaller');
    }

    protected function getBinaries(PackageInterface $package): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getBinaries');
    }

    protected function installFullBinaries(string $binPath, string $link, string $bin, PackageInterface $package): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'installFullBinaries');
    }

    protected function installUnixyProxyBinaries(string $binPath, string $link): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'installUnixyProxyBinaries');
    }

    protected function initializeBinDir(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'initializeBinDir');
    }

    protected function generateWindowsProxyCode(string $bin, string $link): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'generateWindowsProxyCode');
    }

    protected function generateUnixyProxyCode(string $bin, string $link): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'generateUnixyProxyCode');
    }
}
