<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Installer\InstallerEvent.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Installer;

use Composer\Composer;
use Composer\DependencyResolver\Transaction;
use Composer\EventDispatcher\Event;
use Composer\IO\IOInterface;

class InstallerEvent extends Event
{
    public function __construct(string $eventName, Composer $composer, IOInterface $io, bool $devMode, bool $executeOperations, Transaction $transaction)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getComposer(): Composer
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getComposer');
    }

    public function getIO(): IOInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getIO');
    }

    public function isDevMode(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isDevMode');
    }

    public function isExecutingOperations(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isExecutingOperations');
    }

    public function getTransaction(): ?Transaction
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getTransaction');
    }
}
