<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Installer\LibraryInstaller.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Installer;

use Composer\IO\IOInterface;
use Composer\PartialComposer;
use Composer\Repository\InstalledRepositoryInterface;
use Composer\Package\PackageInterface;
use Composer\Util\Filesystem;
use Composer\Downloader\DownloadManager;

class LibraryInstaller implements InstallerInterface, BinaryPresenceInterface
{
    public function __construct(IOInterface $io, PartialComposer $composer, ?string $type = 'library', ?Filesystem $filesystem = null, ?BinaryInstaller $binaryInstaller = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function supports(string $packageType)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'supports');
    }

    public function isInstalled(InstalledRepositoryInterface $repo, PackageInterface $package)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isInstalled');
    }

    public function download(PackageInterface $package, ?PackageInterface $prevPackage = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'download');
    }

    public function prepare($type, PackageInterface $package, ?PackageInterface $prevPackage = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'prepare');
    }

    public function cleanup($type, PackageInterface $package, ?PackageInterface $prevPackage = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'cleanup');
    }

    public function install(InstalledRepositoryInterface $repo, PackageInterface $package)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'install');
    }

    public function update(InstalledRepositoryInterface $repo, PackageInterface $initial, PackageInterface $target)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'update');
    }

    public function uninstall(InstalledRepositoryInterface $repo, PackageInterface $package)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'uninstall');
    }

    public function getInstallPath(PackageInterface $package)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getInstallPath');
    }

    public function ensureBinariesPresence(PackageInterface $package)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'ensureBinariesPresence');
    }

    protected function getPackageBasePath(PackageInterface $package)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPackageBasePath');
    }

    protected function installCode(PackageInterface $package)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'installCode');
    }

    protected function updateCode(PackageInterface $initial, PackageInterface $target)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'updateCode');
    }

    protected function removeCode(PackageInterface $package)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'removeCode');
    }

    protected function initializeVendorDir()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'initializeVendorDir');
    }

    protected function getDownloadManager(): DownloadManager
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getDownloadManager');
    }
}
