<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Installer\PluginInstaller.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Installer;

use Composer\IO\IOInterface;
use Composer\PartialComposer;
use Composer\Repository\InstalledRepositoryInterface;
use Composer\Package\PackageInterface;
use Composer\Plugin\PluginManager;
use Composer\Util\Filesystem;

class PluginInstaller extends LibraryInstaller
{
    public function __construct(IOInterface $io, PartialComposer $composer, ?Filesystem $fs = null, ?BinaryInstaller $binaryInstaller = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function supports(string $packageType)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'supports');
    }

    public function disablePlugins(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'disablePlugins');
    }

    public function prepare($type, PackageInterface $package, ?PackageInterface $prevPackage = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'prepare');
    }

    public function download(PackageInterface $package, ?PackageInterface $prevPackage = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'download');
    }

    public function install(InstalledRepositoryInterface $repo, PackageInterface $package)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'install');
    }

    public function update(InstalledRepositoryInterface $repo, PackageInterface $initial, PackageInterface $target)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'update');
    }

    public function uninstall(InstalledRepositoryInterface $repo, PackageInterface $package)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'uninstall');
    }

    protected function getPluginManager(): PluginManager
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPluginManager');
    }
}
