<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Installer\ProjectInstaller.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Installer;

use React\Promise\PromiseInterface;
use Composer\Package\PackageInterface;
use Composer\Downloader\DownloadManager;
use Composer\Repository\InstalledRepositoryInterface;
use Composer\Util\Filesystem;

class ProjectInstaller implements InstallerInterface
{
    public function __construct(string $installPath, DownloadManager $dm, Filesystem $fs)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function supports(string $packageType): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'supports');
    }

    public function isInstalled(InstalledRepositoryInterface $repo, PackageInterface $package): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isInstalled');
    }

    public function download(PackageInterface $package, ?PackageInterface $prevPackage = null): ?PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'download');
    }

    public function prepare($type, PackageInterface $package, ?PackageInterface $prevPackage = null): ?PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'prepare');
    }

    public function cleanup($type, PackageInterface $package, ?PackageInterface $prevPackage = null): ?PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'cleanup');
    }

    public function install(InstalledRepositoryInterface $repo, PackageInterface $package): ?PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'install');
    }

    public function update(InstalledRepositoryInterface $repo, PackageInterface $initial, PackageInterface $target): ?PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'update');
    }

    public function uninstall(InstalledRepositoryInterface $repo, PackageInterface $package): ?PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'uninstall');
    }

    public function getInstallPath(PackageInterface $package): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getInstallPath');
    }
}
