<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Package\Archiver\ArchivableFilesFinder.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Package\Archiver;

use FilterIterator;

class ArchivableFilesFinder extends FilterIterator
{
    public function __construct(string $sources, array $excludes, bool $ignoreFilters = false)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function accept(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'accept');
    }
}
