<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Package\Archiver\ArchiveManager.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Package\Archiver;

use Composer\Downloader\DownloadManager;
use Composer\Util\Loop;
use Composer\Package\CompletePackageInterface;

class ArchiveManager
{
    public function __construct(DownloadManager $downloadManager, Loop $loop)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function addArchiver(ArchiverInterface $archiver): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'addArchiver');
    }

    public function setOverwriteFiles(bool $overwriteFiles): self
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setOverwriteFiles');
    }

    public function getPackageFilenameParts(CompletePackageInterface $package): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPackageFilenameParts');
    }

    public function getPackageFilenameFromParts(array $parts): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPackageFilenameFromParts');
    }

    public function getPackageFilename(CompletePackageInterface $package): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPackageFilename');
    }

    public function archive(CompletePackageInterface $package, string $format, string $targetDir, ?string $fileName = null, bool $ignoreFilters = false): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'archive');
    }
}
