<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Package\Archiver\PharArchiver.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Package\Archiver;

class PharArchiver implements ArchiverInterface
{
    public function __construct()
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function archive(string $sources, string $target, string $format, array $excludes = [], bool $ignoreFilters = false): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'archive');
    }

    public function supports(string $format, ?string $sourceType): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'supports');
    }
}
