<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Proxy stub for Composer\IO\BufferIO: the public surface forwards to the Rust-side entity over RPC.

namespace Composer\IO;

use Symfony\Component\Console\Output\StreamOutput;
use Symfony\Component\Console\Formatter\OutputFormatterInterface;

class BufferIO extends ConsoleIO
{
    public function __construct(string $input = '', int $verbosity = StreamOutput::VERBOSITY_NORMAL, ?OutputFormatterInterface $formatter = null)
    {
        [$this->__rhandle, $this->__epoch] = \ShirabeRpcRuntime::callRust(0, '__shirabeConstruct', [static::class, [$input, $verbosity, $formatter]]);
        \ShirabeRustObjectRegistry::adopt($this->__rhandle, $this);
    }

    public function getOutput(): string
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getOutput', []);
    }

    public function setUserInputs(array $inputs): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setUserInputs', [$inputs]);
    }
}
