<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Proxy stub for Composer\IO\BufferIO: the public surface forwards to the Rust-side entity over RPC.

namespace Composer\IO;

class BufferIO extends ConsoleIO
{
    public function getOutput(): string
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getOutput', []);
    }

    public function setUserInputs(array $inputs): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setUserInputs', [$inputs]);
    }
}
