<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Proxy stub for Composer\IO\NullIO: the public surface forwards to the Rust-side entity over RPC.

namespace Composer\IO;

class NullIO extends BaseIO
{
}
