[package]
name = "shirabe-php-rpc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Rust-to-PHP RPC over a Unix domain socket"
repository.workspace = true
license.workspace = true

[dependencies]
shirabe-php-shim.workspace = true
shirabe-php-src.workspace = true
shirabe-symfony-process.workspace = true
anyhow.workspace = true
indexmap.workspace = true
nix.workspace = true
tempfile.workspace = true

[lints]
workspace = true
