<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Proxy stub for Composer\Repository\InstalledArrayRepository: the public surface forwards to the Rust-side entity over RPC.

namespace Composer\Repository;

class InstalledArrayRepository extends WritableArrayRepository implements InstalledRepositoryInterface
{
    public function isFresh(): bool
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'isFresh', []);
    }
}
