<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Proxy stub for Composer\Repository\InstalledFilesystemRepository: the public surface forwards to the Rust-side entity over RPC.

namespace Composer\Repository;

class InstalledFilesystemRepository extends FilesystemRepository implements InstalledRepositoryInterface
{
    public function isFresh()
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'isFresh', []);
    }
}
