<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Proxy stub for Composer\Repository\WritableArrayRepository: the public surface forwards to the Rust-side entity over RPC.

namespace Composer\Repository;

use Composer\Installer\InstallationManager;

class WritableArrayRepository extends ArrayRepository implements WritableRepositoryInterface
{
    public function write(bool $devMode, InstallationManager $installationManager)
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'write', [$devMode, $installationManager]);
    }

    public function getCanonicalPackages()
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getCanonicalPackages', []);
    }

    public function reload()
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'reload', []);
    }

    public function setDevPackageNames(array $devPackageNames)
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'setDevPackageNames', [$devPackageNames]);
    }

    public function getDevPackageNames()
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getDevPackageNames', []);
    }

    public function getDevMode()
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getDevMode', []);
    }
}
