<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Downloader\FileDownloader.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Downloader;

use Composer\Config;
use Composer\Cache;
use Composer\IO\IOInterface;
use Composer\Package\PackageInterface;
use Composer\EventDispatcher\EventDispatcher;
use Composer\Util\Filesystem;
use Composer\Util\HttpDownloader;
use Composer\Util\ProcessExecutor;
use React\Promise\PromiseInterface;

class FileDownloader implements DownloaderInterface, ChangeReportInterface
{
    public static $downloadMetadata = [];
    public static $responseHeaders = [];

    public function __construct(IOInterface $io, Config $config, HttpDownloader $httpDownloader, ?EventDispatcher $eventDispatcher = null, ?Cache $cache = null, ?Filesystem $filesystem = null, ?ProcessExecutor $process = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getInstallationSource(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getInstallationSource');
    }

    public function download(PackageInterface $package, string $path, ?PackageInterface $prevPackage = null, bool $output = true): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'download');
    }

    public function prepare(string $type, PackageInterface $package, string $path, ?PackageInterface $prevPackage = null): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'prepare');
    }

    public function cleanup(string $type, PackageInterface $package, string $path, ?PackageInterface $prevPackage = null): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'cleanup');
    }

    public function install(PackageInterface $package, string $path, bool $output = true): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'install');
    }

    protected function getDistPath(PackageInterface $package, int $component): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getDistPath');
    }

    protected function clearLastCacheWrite(PackageInterface $package): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'clearLastCacheWrite');
    }

    protected function addCleanupPath(PackageInterface $package, string $path): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'addCleanupPath');
    }

    protected function removeCleanupPath(PackageInterface $package, string $path): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'removeCleanupPath');
    }

    public function update(PackageInterface $initial, PackageInterface $target, string $path): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'update');
    }

    public function remove(PackageInterface $package, string $path, bool $output = true): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'remove');
    }

    protected function getFileName(PackageInterface $package, string $path): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getFileName');
    }

    protected function getInstallOperationAppendix(PackageInterface $package, string $path): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getInstallOperationAppendix');
    }

    protected function processUrl(PackageInterface $package, string $url): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'processUrl');
    }

    public function getLocalChanges(PackageInterface $package, string $path): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getLocalChanges');
    }
}
