<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Downloader\HgDownloader.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Downloader;

use React\Promise\PromiseInterface;
use Composer\Package\PackageInterface;

class HgDownloader extends VcsDownloader
{
    protected function doDownload(PackageInterface $package, string $path, string $url, ?PackageInterface $prevPackage = null): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'doDownload');
    }

    protected function doInstall(PackageInterface $package, string $path, string $url): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'doInstall');
    }

    protected function doUpdate(PackageInterface $initial, PackageInterface $target, string $path, string $url): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'doUpdate');
    }

    public function getLocalChanges(PackageInterface $package, string $path): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getLocalChanges');
    }

    protected function getCommitLogs(string $fromReference, string $toReference, string $path): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getCommitLogs');
    }

    protected function hasMetadataRepository(string $path): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'hasMetadataRepository');
    }

    public function __construct(IOInterface $io, Config $config, ?ProcessExecutor $process = null, ?Filesystem $fs = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getInstallationSource(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getInstallationSource');
    }

    public function download(PackageInterface $package, string $path, ?PackageInterface $prevPackage = null): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'download');
    }

    public function prepare(string $type, PackageInterface $package, string $path, ?PackageInterface $prevPackage = null): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'prepare');
    }

    public function cleanup(string $type, PackageInterface $package, string $path, ?PackageInterface $prevPackage = null): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'cleanup');
    }

    public function install(PackageInterface $package, string $path): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'install');
    }

    public function update(PackageInterface $initial, PackageInterface $target, string $path): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'update');
    }

    public function remove(PackageInterface $package, string $path): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'remove');
    }

    public function getVcsReference(PackageInterface $package, string $path): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getVcsReference');
    }

    protected function cleanChanges(PackageInterface $package, string $path, bool $update): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'cleanChanges');
    }

    protected function reapplyChanges(string $path): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'reapplyChanges');
    }
}
