<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Downloader\PathDownloader.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Downloader;

use React\Promise\PromiseInterface;
use Composer\Package\PackageInterface;

class PathDownloader extends FileDownloader implements VcsCapableDownloaderInterface
{
    private const STRATEGY_SYMLINK = 10;
    private const STRATEGY_MIRROR = 20;

    public function __construct()
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function download(PackageInterface $package, string $path, ?PackageInterface $prevPackage = null, bool $output = true): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'download');
    }

    public function install(PackageInterface $package, string $path, bool $output = true): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'install');
    }

    public function remove(PackageInterface $package, string $path, bool $output = true): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'remove');
    }

    public function getVcsReference(PackageInterface $package, string $path): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getVcsReference');
    }

    protected function getInstallOperationAppendix(PackageInterface $package, string $path): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getInstallOperationAppendix');
    }
}
