<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Downloader\ZipDownloader.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Downloader;

use Composer\Package\PackageInterface;
use React\Promise\PromiseInterface;

class ZipDownloader extends ArchiveDownloader
{
    public function __construct()
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function download(PackageInterface $package, string $path, ?PackageInterface $prevPackage = null, bool $output = true): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'download');
    }

    protected function extract(PackageInterface $package, string $file, string $path): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'extract');
    }

    protected function getErrorMessage(int $retval, string $file): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getErrorMessage');
    }

    public function prepare(string $type, PackageInterface $package, string $path, ?PackageInterface $prevPackage = null): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'prepare');
    }

    public function cleanup(string $type, PackageInterface $package, string $path, ?PackageInterface $prevPackage = null): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'cleanup');
    }

    public function install(PackageInterface $package, string $path, bool $output = true): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'install');
    }

    protected function getInstallOperationAppendix(PackageInterface $package, string $path): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getInstallOperationAppendix');
    }
}
