<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Util\Http\CurlResponse.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Util\Http;

class CurlResponse extends Response
{
    public function __construct(array $request, ?int $code, array $headers, ?string $body, array $curlInfo)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getCurlInfo(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getCurlInfo');
    }

    public function getStatusCode(): int
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getStatusCode');
    }

    public function getStatusMessage(): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getStatusMessage');
    }

    public function getHeaders(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getHeaders');
    }

    public function getHeader(string $name): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getHeader');
    }

    public function getBody(): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getBody');
    }

    public function decodeJson()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'decodeJson');
    }

    public function collect(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'collect');
    }

    public static function findHeaderValue(array $headers, string $name): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'findHeaderValue');
    }
}
