<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Util\Http\CurlDownloader.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Util\Http;

use Composer\Config;
use Composer\IO\IOInterface;

class CurlDownloader
{
    private const BAD_MULTIPLEXING_CURL_VERSIONS = ['7.87.0', '7.88.0', '7.88.1'];

    public function __construct(IOInterface $io, Config $config, array $options = [], bool $disableTls = false)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function download(callable $resolve, callable $reject, string $origin, string $url, array $options, ?string $copyTo = null): int
    {
        \ShirabeUnsupportedClass::fail(self::class, 'download');
    }

    public function abortRequest(int $id): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'abortRequest');
    }

    public function tick(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'tick');
    }
}
