<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Plugin\CommandEvent.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Plugin;

use Composer\EventDispatcher\Event;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class CommandEvent extends Event
{
    public function __construct(string $name, string $commandName, InputInterface $input, OutputInterface $output, array $args = [], array $flags = [])
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getInput(): InputInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getInput');
    }

    public function getOutput(): OutputInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getOutput');
    }

    public function getCommandName(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getCommandName');
    }
}
