<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Plugin\PluginManager.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Plugin;

use Composer\Composer;
use Composer\IO\IOInterface;
use Composer\PartialComposer;
use Composer\Package\PackageInterface;
use Composer\Plugin\Capability\Capability;

class PluginManager
{
    public function __construct(IOInterface $io, Composer $composer, ?PartialComposer $globalComposer = null, $disablePlugins = false)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function setRunningInGlobalDir(bool $runningInGlobalDir): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setRunningInGlobalDir');
    }

    public function loadInstalledPlugins(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'loadInstalledPlugins');
    }

    public function deactivateInstalledPlugins(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'deactivateInstalledPlugins');
    }

    public function getPlugins(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPlugins');
    }

    public function getRegisteredPlugins(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRegisteredPlugins');
    }

    public function getGlobalComposer(): ?PartialComposer
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getGlobalComposer');
    }

    public function registerPackage(PackageInterface $package, bool $failOnMissingClasses = false, bool $isGlobalPlugin = false): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'registerPackage');
    }

    public function deactivatePackage(PackageInterface $package): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'deactivatePackage');
    }

    public function uninstallPackage(PackageInterface $package): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'uninstallPackage');
    }

    protected function getPluginApiVersion(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPluginApiVersion');
    }

    public function addPlugin(PluginInterface $plugin, bool $isGlobalPlugin = false, ?PackageInterface $sourcePackage = null): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'addPlugin');
    }

    public function removePlugin(PluginInterface $plugin): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'removePlugin');
    }

    public function uninstallPlugin(PluginInterface $plugin): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'uninstallPlugin');
    }

    protected function getCapabilityImplementationClassName(PluginInterface $plugin, string $capability): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getCapabilityImplementationClassName');
    }

    public function getPluginCapability(PluginInterface $plugin, $capabilityClassName, array $ctorArgs = []): ?Capability
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPluginCapability');
    }

    public function getPluginCapabilities($capabilityClassName, array $ctorArgs = []): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPluginCapabilities');
    }

    public function arePluginsDisabled($type)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'arePluginsDisabled');
    }

    public function disablePlugins(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'disablePlugins');
    }

    public function isPluginAllowed(string $package, bool $isGlobalPlugin, bool $optional = false, bool $prompt = true): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isPluginAllowed');
    }
}
