<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Plugin\PostFileDownloadEvent.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Plugin;

use Composer\EventDispatcher\Event;
use Composer\Package\PackageInterface;

class PostFileDownloadEvent extends Event
{
    public function __construct(string $name, ?string $fileName, ?string $checksum, string $url, string $type, $context = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getFileName(): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getFileName');
    }

    public function getChecksum(): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getChecksum');
    }

    public function getUrl(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getUrl');
    }

    public function getContext()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getContext');
    }

    public function getPackage(): ?PackageInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPackage');
    }

    public function getType(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getType');
    }
}
