<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Plugin\PreFileDownloadEvent.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Plugin;

use Composer\EventDispatcher\Event;
use Composer\Util\HttpDownloader;

class PreFileDownloadEvent extends Event
{
    public function __construct(string $name, HttpDownloader $httpDownloader, string $processedUrl, string $type, $context = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getHttpDownloader(): HttpDownloader
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getHttpDownloader');
    }

    public function getProcessedUrl(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getProcessedUrl');
    }

    public function setProcessedUrl(string $processedUrl): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setProcessedUrl');
    }

    public function getCustomCacheKey(): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getCustomCacheKey');
    }

    public function setCustomCacheKey(?string $customCacheKey): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setCustomCacheKey');
    }

    public function getType(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getType');
    }

    public function getContext()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getContext');
    }

    public function getTransportOptions(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getTransportOptions');
    }

    public function setTransportOptions(array $options): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setTransportOptions');
    }
}
