<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Plugin\PrePoolCreateEvent.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Plugin;

use Composer\EventDispatcher\Event;
use Composer\DependencyResolver\Request;

class PrePoolCreateEvent extends Event
{
    public function __construct(string $name, array $repositories, Request $request, array $acceptableStabilities, array $stabilityFlags, array $rootAliases, array $rootReferences, array $packages, array $unacceptableFixedPackages)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getRepositories(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRepositories');
    }

    public function getRequest(): Request
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRequest');
    }

    public function getAcceptableStabilities(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getAcceptableStabilities');
    }

    public function getStabilityFlags(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getStabilityFlags');
    }

    public function getRootAliases(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRootAliases');
    }

    public function getRootReferences(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRootReferences');
    }

    public function getPackages(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPackages');
    }

    public function getUnacceptableFixedPackages(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getUnacceptableFixedPackages');
    }

    public function setPackages(array $packages): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setPackages');
    }

    public function setUnacceptableFixedPackages(array $packages): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setUnacceptableFixedPackages');
    }
}
