<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Proxy stub for Composer\Installer\PackageEvent: the public surface forwards to the Rust-side entity over RPC.

namespace Composer\Installer;

use Composer\Composer;
use Composer\IO\IOInterface;
use Composer\DependencyResolver\Operation\OperationInterface;
use Composer\Repository\RepositoryInterface;
use Composer\EventDispatcher\Event;

class PackageEvent extends Event
{
    public function __construct(string $eventName, Composer $composer, IOInterface $io, bool $devMode, RepositoryInterface $localRepo, array $operations, OperationInterface $operation)
    {
        [$this->__rhandle, $this->__epoch] = \ShirabeRpcRuntime::callRust(0, '__shirabeConstruct', [static::class, [$eventName, $composer, $io, $devMode, $localRepo, $operations, $operation]]);
        \ShirabeRustObjectRegistry::adopt($this->__rhandle, $this);
    }

    public function getComposer(): Composer
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getComposer', []);
    }

    public function getIO(): IOInterface
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getIO', []);
    }

    public function isDevMode(): bool
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'isDevMode', []);
    }

    public function getLocalRepo(): RepositoryInterface
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getLocalRepo', []);
    }

    public function getOperations(): array
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getOperations', []);
    }

    public function getOperation(): OperationInterface
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getOperation', []);
    }
}
