<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Proxy stub for Composer\DependencyResolver\Operation\MarkAliasInstalledOperation: the public surface forwards to the Rust-side entity over RPC.

namespace Composer\DependencyResolver\Operation;

use Composer\Package\AliasPackage;

class MarkAliasInstalledOperation extends SolverOperation implements OperationInterface
{
    public function __construct(AliasPackage $package)
    {
        [$this->__rhandle, $this->__epoch] = \ShirabeRpcRuntime::callRust(0, '__shirabeConstruct', [static::class, [$package]]);
        \ShirabeRustObjectRegistry::adopt($this->__rhandle, $this);
    }

    protected const TYPE = 'markAliasInstalled';

    public function getPackage(): AliasPackage
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getPackage', []);
    }
}
