<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Proxy stub for Composer\DependencyResolver\Operation\SolverOperation: the public surface forwards to the Rust-side entity over RPC.

namespace Composer\DependencyResolver\Operation;

abstract class SolverOperation implements OperationInterface, \ShirabeRustStub
{
    /** @var int */
    protected $__rhandle;
    /** @var int */
    protected $__epoch;

    /**
     * Binds a stub the registry built for an existing entity. Proxy instantiation bypasses
     * the constructor, which belongs to plugin code building a new entity instead.
     */
    public function __shirabeBind(int $rhandle, int $epoch): void
    {
        $this->__rhandle = $rhandle;
        $this->__epoch = $epoch;
    }

    public function __destruct()
    {
        \ShirabeRustObjectRegistry::release($this->__rhandle);
    }

    public function __shirabeRustHandleDescriptor(): array
    {
        return [
            '__rhandle' => $this->__rhandle,
            '__class' => static::class,
            '__epoch' => $this->__epoch,
        ];
    }

    public function __clone()
    {
        // PHP has already shallow-copied this stub, so both copies would point at one
        // entity and release it twice. The Rust side clones the entity instead, applying
        // whatever __clone semantics the real class defines, and this copy rebinds to the
        // fresh handle. Entities without clone semantics answer with an explicit error.
        [$this->__rhandle, $this->__epoch] = \ShirabeRpcRuntime::callRust($this->__rhandle, '__shirabeClone', []);
        \ShirabeRustObjectRegistry::adopt($this->__rhandle, $this);
    }

    public function __get($name)
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, '__get', [$name]);
    }

    public function __set($name, $value): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, '__set', [$name, $value]);
    }

    public function __isset($name): bool
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, '__isset', [$name]);
    }

    public function __unset($name): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, '__unset', [$name]);
    }

    public function __construct()
    {
        [$this->__rhandle, $this->__epoch] = \ShirabeRpcRuntime::callRust(0, '__shirabeConstruct', [static::class, []]);
        \ShirabeRustObjectRegistry::adopt($this->__rhandle, $this);
    }

    protected const TYPE = '';

    public function getOperationType(): string
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getOperationType', []);
    }

    public function show(bool $lock)
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'show', [$lock]);
    }

    public function __toString()
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, '__toString', []);
    }
}
