<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Proxy stub for Composer\DependencyResolver\Operation\UninstallOperation: the public surface forwards to the Rust-side entity over RPC.

namespace Composer\DependencyResolver\Operation;

use Composer\Package\PackageInterface;

class UninstallOperation extends SolverOperation implements OperationInterface
{
    public function __construct(PackageInterface $package)
    {
        [$this->__rhandle, $this->__epoch] = \ShirabeRpcRuntime::callRust(0, '__shirabeConstruct', [static::class, [$package]]);
        \ShirabeRustObjectRegistry::adopt($this->__rhandle, $this);
    }

    protected const TYPE = 'uninstall';

    public static function format(PackageInterface $package, bool $lock = false): string
    {
        return 'Removing <info>'.$package->getPrettyName().'</info> (<comment>'.$package->getFullPrettyVersion().'</comment>)';
    }

    public function getPackage(): PackageInterface
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getPackage', []);
    }
}
