<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Cache.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer;

use Composer\IO\IOInterface;
use Composer\Util\Filesystem;

class Cache
{
    public function __construct(IOInterface $io, string $cacheDir, string $allowlist = 'a-z0-9._', ?Filesystem $filesystem = null, bool $readOnly = false)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function setReadOnly(bool $readOnly)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setReadOnly');
    }

    public function isReadOnly()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isReadOnly');
    }

    public static function isUsable(string $path)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isUsable');
    }

    public function isEnabled()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isEnabled');
    }

    public function getRoot()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRoot');
    }

    public function read(string $file)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'read');
    }

    public function write(string $file, string $contents)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'write');
    }

    public function copyFrom(string $file, string $source)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'copyFrom');
    }

    public function copyTo(string $file, string $target)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'copyTo');
    }

    public function gcIsNecessary()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'gcIsNecessary');
    }

    public function remove(string $file)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'remove');
    }

    public function clear()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'clear');
    }

    public function getAge(string $file)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getAge');
    }

    public function gc(int $ttl, int $maxSize)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'gc');
    }

    public function gcVcsCache(int $ttl): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'gcVcsCache');
    }

    public function sha1(string $file)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'sha1');
    }

    public function sha256(string $file)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'sha256');
    }

    protected function getFinder()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getFinder');
    }
}
