<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Factory.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer;

use Composer\IO\IOInterface;
use Composer\Package\Version\VersionGuesser;
use Composer\Package\RootPackageInterface;
use Composer\Repository\RepositoryManager;
use Composer\Util\ProcessExecutor;
use Composer\Util\HttpDownloader;
use Composer\Util\Loop;
use Symfony\Component\Console\Output\ConsoleOutput;
use Composer\EventDispatcher\EventDispatcher;
use Composer\Package\Version\VersionParser;
use Composer\Repository\InstalledRepositoryInterface;

class Factory
{
    public function __construct()
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    protected static function getHomeDir(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getHomeDir');
    }

    protected static function getCacheDir(string $home): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getCacheDir');
    }

    protected static function getDataDir(string $home): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getDataDir');
    }

    public static function createConfig(?IOInterface $io = null, ?string $cwd = null): Config
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createConfig');
    }

    public static function getComposerFile(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getComposerFile');
    }

    public static function getLockFile(string $composerFile): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getLockFile');
    }

    public static function createAdditionalStyles(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createAdditionalStyles');
    }

    public static function createOutput(): ConsoleOutput
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createOutput');
    }

    public function createComposer(IOInterface $io, $localConfig = null, $disablePlugins = false, ?string $cwd = null, bool $fullLoad = true, bool $disableScripts = false)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createComposer');
    }

    public static function createGlobal(IOInterface $io, bool $disablePlugins = false, bool $disableScripts = false): ?Composer
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createGlobal');
    }

    protected function addLocalRepository(IOInterface $io, RepositoryManager $rm, string $vendorDir, RootPackageInterface $rootPackage, ?ProcessExecutor $process = null): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'addLocalRepository');
    }

    protected function createGlobalComposer(IOInterface $io, Config $config, $disablePlugins, bool $disableScripts, bool $fullLoad = false): ?PartialComposer
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createGlobalComposer');
    }

    public function createDownloadManager(IOInterface $io, Config $config, HttpDownloader $httpDownloader, ProcessExecutor $process, ?EventDispatcher $eventDispatcher = null): \Composer\Downloader\DownloadManager
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createDownloadManager');
    }

    public function createArchiveManager(Config $config, \Composer\Downloader\DownloadManager $dm, Loop $loop)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createArchiveManager');
    }

    protected function createPluginManager(IOInterface $io, Composer $composer, ?PartialComposer $globalComposer = null, $disablePlugins = false): \Composer\Plugin\PluginManager
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createPluginManager');
    }

    public function createInstallationManager(Loop $loop, IOInterface $io, ?EventDispatcher $eventDispatcher = null): \Composer\Installer\InstallationManager
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createInstallationManager');
    }

    protected function createDefaultInstallers(\Composer\Installer\InstallationManager $im, PartialComposer $composer, IOInterface $io, ?ProcessExecutor $process = null): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createDefaultInstallers');
    }

    protected function purgePackages(InstalledRepositoryInterface $repo, \Composer\Installer\InstallationManager $im): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'purgePackages');
    }

    protected function loadRootPackage(RepositoryManager $rm, Config $config, VersionParser $parser, VersionGuesser $guesser, IOInterface $io): \Composer\Package\Loader\RootPackageLoader
    {
        \ShirabeUnsupportedClass::fail(self::class, 'loadRootPackage');
    }

    public static function create(IOInterface $io, $config = null, $disablePlugins = false, bool $disableScripts = false): Composer
    {
        \ShirabeUnsupportedClass::fail(self::class, 'create');
    }

    public static function createHttpDownloader(IOInterface $io, Config $config, array $options = []): HttpDownloader
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createHttpDownloader');
    }
}
