<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Proxy stub for Composer\EventDispatcher\Event: the public surface forwards to the Rust-side entity over RPC.

namespace Composer\EventDispatcher;

class Event implements \ShirabeRustStub
{
    /** @var int */
    protected $__rhandle;
    /** @var int */
    protected $__epoch;

    public function __construct(int $rhandle = 0, int $epoch = 0)
    {
        if (func_num_args() < 2) {
            // Constructing the class from plugin code (a common idiom for e.g. `new BufferIO()`)
            // is an open question of the plugin design; only proxy instantiation passes a
            // Rust handle. Fail with a diagnosable message instead of an ArgumentCountError.
            throw new \RuntimeException(
                'Shirabe does not support constructing ' . static::class . ' inside the plugin process yet'
            );
        }
        $this->__rhandle = $rhandle;
        $this->__epoch = $epoch;
    }

    public function __destruct()
    {
        \ShirabeRustObjectRegistry::release($this->__rhandle);
    }

    public function __shirabeRustHandleDescriptor(): array
    {
        return [
            '__rhandle' => $this->__rhandle,
            '__class' => static::class,
            '__epoch' => $this->__epoch,
        ];
    }

    public function getName(): string
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getName', []);
    }

    public function getArguments(): array
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getArguments', []);
    }

    public function getFlags(): array
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getFlags', []);
    }

    public function isPropagationStopped(): bool
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'isPropagationStopped', []);
    }

    public function stopPropagation(): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'stopPropagation', []);
    }
}
