<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Autoload\AutoloadGenerator.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Autoload;

use Composer\Config;
use Composer\EventDispatcher\EventDispatcher;
use Composer\Filter\PlatformRequirementFilter\PlatformRequirementFilterInterface;
use Composer\Installer\InstallationManager;
use Composer\IO\IOInterface;
use Composer\Package\PackageInterface;
use Composer\Package\RootPackageInterface;
use Composer\Repository\InstalledRepositoryInterface;
use Composer\Util\Filesystem;
use Composer\Package\Locker;

class AutoloadGenerator
{
    public function __construct(EventDispatcher $eventDispatcher, ?IOInterface $io = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function setDevMode(bool $devMode = true)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setDevMode');
    }

    public function setClassMapAuthoritative(bool $classMapAuthoritative)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setClassMapAuthoritative');
    }

    public function setApcu(bool $apcu, ?string $apcuPrefix = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setApcu');
    }

    public function setRunScripts(bool $runScripts = true)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setRunScripts');
    }

    public function setDryRun(bool $dryRun = true): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setDryRun');
    }

    public function setIgnorePlatformRequirements($ignorePlatformReqs)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setIgnorePlatformRequirements');
    }

    public function setPlatformRequirementFilter(PlatformRequirementFilterInterface $platformRequirementFilter)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setPlatformRequirementFilter');
    }

    public function dump(Config $config, InstalledRepositoryInterface $localRepo, RootPackageInterface $rootPackage, InstallationManager $installationManager, string $targetDir, bool $scanPsrPackages = false, ?string $suffix = null, ?Locker $locker = null, bool $strictAmbiguous = false)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'dump');
    }

    public function buildPackageMap(InstallationManager $installationManager, PackageInterface $rootPackage, array $packages)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'buildPackageMap');
    }

    protected function validatePackage(PackageInterface $package)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'validatePackage');
    }

    public function parseAutoloads(array $packageMap, PackageInterface $rootPackage, $filteredDevPackages = false)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'parseAutoloads');
    }

    public function createLoader(array $autoloads, ?string $vendorDir = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createLoader');
    }

    protected function getIncludePathsFile(array $packageMap, Filesystem $filesystem, string $basePath, string $vendorPath, string $vendorPathCode, string $appBaseDirCode)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getIncludePathsFile');
    }

    protected function getIncludeFilesFile(array $files, Filesystem $filesystem, string $basePath, string $vendorPath, string $vendorPathCode, string $appBaseDirCode)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getIncludeFilesFile');
    }

    protected function getPathCode(Filesystem $filesystem, string $basePath, string $vendorPath, string $path)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPathCode');
    }

    protected function getPlatformCheck(array $packageMap, $checkPlatform, array $devPackageNames)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPlatformCheck');
    }

    protected function getAutoloadFile(string $vendorPathToTargetDirCode, string $suffix)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getAutoloadFile');
    }

    protected function getAutoloadRealFile(bool $useClassMap, bool $useIncludePath, ?string $targetDirLoader, bool $useIncludeFiles, string $vendorPathCode, string $appBaseDirCode, string $suffix, bool $useGlobalIncludePath, string $prependAutoloader, bool $checkPlatform)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getAutoloadRealFile');
    }

    protected function getStaticFile(string $suffix, string $targetDir, string $vendorPath, string $basePath)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getStaticFile');
    }

    protected function parseAutoloadsType(array $packageMap, string $type, RootPackageInterface $rootPackage)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'parseAutoloadsType');
    }

    protected function getFileIdentifier(PackageInterface $package, string $path)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getFileIdentifier');
    }

    protected function filterPackageMap(array $packageMap, RootPackageInterface $rootPackage)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'filterPackageMap');
    }

    protected function sortPackageMap(array $packageMap)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'sortPackageMap');
    }
}
