<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Package\Locker.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Package;

use Composer\Json\JsonFile;
use Composer\Installer\InstallationManager;
use Composer\Repository\LockArrayRepository;
use Composer\Util\ProcessExecutor;
use Composer\IO\IOInterface;

class Locker
{
    public function __construct(IOInterface $io, JsonFile $lockFile, InstallationManager $installationManager, string $composerFileContents, ?ProcessExecutor $process = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getJsonFile(): JsonFile
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getJsonFile');
    }

    public static function getContentHash(string $composerFileContents): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getContentHash');
    }

    public function isLocked(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isLocked');
    }

    public function isFresh(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isFresh');
    }

    public function getLockedRepository(bool $withDevReqs = false): LockArrayRepository
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getLockedRepository');
    }

    public function getDevPackageNames(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getDevPackageNames');
    }

    public function getPlatformRequirements(bool $withDevReqs = false): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPlatformRequirements');
    }

    public function getMinimumStability(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getMinimumStability');
    }

    public function getStabilityFlags(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getStabilityFlags');
    }

    public function getPreferStable(): ?bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPreferStable');
    }

    public function getPreferLowest(): ?bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPreferLowest');
    }

    public function getPlatformOverrides(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPlatformOverrides');
    }

    public function getAliases(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getAliases');
    }

    public function getPluginApi()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPluginApi');
    }

    public function getLockData(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getLockData');
    }

    public function setLockData(array $packages, ?array $devPackages, array $platformReqs, array $platformDevReqs, array $aliases, string $minimumStability, array $stabilityFlags, bool $preferStable, bool $preferLowest, array $platformOverrides, bool $write = true): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setLockData');
    }

    public function updateHash(JsonFile $composerJson, ?callable $dataProcessor = null): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'updateHash');
    }

    public function getMissingRequirementInfo(RootPackageInterface $package, bool $includeDev): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getMissingRequirementInfo');
    }
}
