<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\DependencyResolver\DefaultPolicy.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\DependencyResolver;

use Composer\Package\BasePackage;
use Composer\Package\PackageInterface;

class DefaultPolicy implements PolicyInterface
{
    public function __construct(bool $preferStable = false, bool $preferLowest = false, ?array $preferredVersions = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function versionCompare(PackageInterface $a, PackageInterface $b, string $operator): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'versionCompare');
    }

    public function selectPreferredPackages(Pool $pool, array $literals, ?string $requiredPackage = null): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'selectPreferredPackages');
    }

    protected function groupLiteralsByName(Pool $pool, array $literals): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'groupLiteralsByName');
    }

    public function compareByPriority(Pool $pool, BasePackage $a, BasePackage $b, ?string $requiredPackage = null, bool $ignoreReplace = false): int
    {
        \ShirabeUnsupportedClass::fail(self::class, 'compareByPriority');
    }

    protected function replaces(BasePackage $source, BasePackage $target): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'replaces');
    }

    protected function pruneToBestVersion(Pool $pool, array $literals): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'pruneToBestVersion');
    }

    protected function pruneRemoteAliases(Pool $pool, array $literals): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'pruneRemoteAliases');
    }
}
