<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\DependencyResolver\GenericRule.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\DependencyResolver;

class GenericRule extends Rule
{
    public function __construct(array $literals, $reason, $reasonData)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getLiterals(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getLiterals');
    }

    public function getHash()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getHash');
    }

    public function equals(Rule $rule): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'equals');
    }

    public function isAssertion(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isAssertion');
    }

    public function __toString(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, '__toString');
    }

    public function getReason(): int
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getReason');
    }

    public function getReasonData()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getReasonData');
    }

    public function getRequiredPackage(): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRequiredPackage');
    }

    public function setType($type): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setType');
    }

    public function getType(): int
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getType');
    }

    public function disable(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'disable');
    }

    public function enable(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'enable');
    }

    public function isDisabled(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isDisabled');
    }

    public function isEnabled(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isEnabled');
    }

    public function isCausedByLock(RepositorySet $repositorySet, Request $request, Pool $pool): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isCausedByLock');
    }

    public function getSourcePackage(Pool $pool): BasePackage
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getSourcePackage');
    }

    public function getPrettyString(RepositorySet $repositorySet, Request $request, Pool $pool, bool $isVerbose, array $installedMap = [], array $learnedPool = []): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPrettyString');
    }

    protected function formatPackagesUnique(Pool $pool, array $literalsOrPackages, bool $isVerbose, ?ConstraintInterface $constraint = null, bool $useRemovedVersionGroup = false): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'formatPackagesUnique');
    }
}
