<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\DependencyResolver\LockTransaction.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\DependencyResolver;

class LockTransaction extends Transaction
{
    public function __construct(Pool $pool, array $presentMap, array $unlockableMap, Decisions $decisions)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function setResultPackages(Pool $pool, Decisions $decisions): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setResultPackages');
    }

    public function setNonDevPackages(LockTransaction $extractionResult): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setNonDevPackages');
    }

    public function getNewLockPackages(bool $devMode, bool $updateMirrors = false): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getNewLockPackages');
    }

    public function getAliases(array $aliases): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getAliases');
    }
}
