<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\DependencyResolver\PoolBuilder.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\DependencyResolver;

use Composer\EventDispatcher\EventDispatcher;
use Composer\IO\IOInterface;

class PoolBuilder
{
    private const LOAD_BATCH_SIZE = 50;

    public function __construct(array $acceptableStabilities, array $stabilityFlags, array $rootAliases, array $rootReferences, IOInterface $io, ?EventDispatcher $eventDispatcher = null, ?PoolOptimizer $poolOptimizer = null, array $temporaryConstraints = [], ?SecurityAdvisoryPoolFilter $securityAdvisoryPoolFilter = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function setIgnoredTypes(array $types): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setIgnoredTypes');
    }

    public function setAllowedTypes(?array $types): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setAllowedTypes');
    }

    public function buildPool(array $repositories, Request $request): Pool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'buildPool');
    }
}
