<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\DependencyResolver\PoolOptimizer.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\DependencyResolver;

class PoolOptimizer
{
    public function __construct(PolicyInterface $policy)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function optimize(Request $request, Pool $pool): Pool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'optimize');
    }
}
