<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\DependencyResolver\Pool.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\DependencyResolver;

use Composer\Package\BasePackage;
use Composer\Semver\Constraint\ConstraintInterface;

class Pool implements \Countable
{
    public function __construct(array $packages = [], array $unacceptableFixedOrLockedPackages = [], array $removedVersions = [], array $removedVersionsByPackage = [], array $securityRemovedVersions = [], array $abandonedRemovedVersions = [])
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getRemovedVersions(string $name, ConstraintInterface $constraint): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRemovedVersions');
    }

    public function getAllRemovedVersions(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getAllRemovedVersions');
    }

    public function getRemovedVersionsByPackage(string $objectHash): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRemovedVersionsByPackage');
    }

    public function getAllRemovedVersionsByPackage(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getAllRemovedVersionsByPackage');
    }

    public function isSecurityRemovedPackageVersion(string $packageName, ?ConstraintInterface $constraint): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isSecurityRemovedPackageVersion');
    }

    public function getSecurityAdvisoryIdentifiersForPackageVersion(string $packageName, ?ConstraintInterface $constraint): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getSecurityAdvisoryIdentifiersForPackageVersion');
    }

    public function isAbandonedRemovedPackageVersion(string $packageName, ?ConstraintInterface $constraint): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isAbandonedRemovedPackageVersion');
    }

    public function getAllSecurityRemovedPackageVersions(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getAllSecurityRemovedPackageVersions');
    }

    public function getAllAbandonedRemovedPackageVersions(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getAllAbandonedRemovedPackageVersions');
    }

    public function getPackages(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPackages');
    }

    public function packageById(int $id): BasePackage
    {
        \ShirabeUnsupportedClass::fail(self::class, 'packageById');
    }

    public function count(): int
    {
        \ShirabeUnsupportedClass::fail(self::class, 'count');
    }

    public function whatProvides(string $name, ?ConstraintInterface $constraint = null): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'whatProvides');
    }

    public function literalToPackage(int $literal): BasePackage
    {
        \ShirabeUnsupportedClass::fail(self::class, 'literalToPackage');
    }

    public function literalToPrettyString(int $literal, array $installedMap): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'literalToPrettyString');
    }

    public function match(BasePackage $candidate, string $name, ?ConstraintInterface $constraint = null): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'match');
    }

    public function isUnacceptableFixedOrLockedPackage(BasePackage $package): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isUnacceptableFixedOrLockedPackage');
    }

    public function getUnacceptableFixedOrLockedPackages(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getUnacceptableFixedOrLockedPackages');
    }

    public function __toString(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, '__toString');
    }
}
