<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\DependencyResolver\Request.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\DependencyResolver;

use Composer\Package\BasePackage;
use Composer\Package\PackageInterface;
use Composer\Repository\LockArrayRepository;
use Composer\Semver\Constraint\ConstraintInterface;

class Request
{
    public const UPDATE_ONLY_LISTED = 0;
    public const UPDATE_LISTED_WITH_TRANSITIVE_DEPS_NO_ROOT_REQUIRE = 1;
    public const UPDATE_LISTED_WITH_TRANSITIVE_DEPS = 2;

    public function __construct(?LockArrayRepository $lockedRepository = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function requireName(string $packageName, ?ConstraintInterface $constraint = null): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'requireName');
    }

    public function fixPackage(BasePackage $package): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'fixPackage');
    }

    public function lockPackage(BasePackage $package): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'lockPackage');
    }

    public function fixLockedPackage(BasePackage $package): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'fixLockedPackage');
    }

    public function unlockPackage(BasePackage $package): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'unlockPackage');
    }

    public function setUpdateAllowList(array $updateAllowList, $updateAllowTransitiveDependencies): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setUpdateAllowList');
    }

    public function getUpdateAllowList(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getUpdateAllowList');
    }

    public function getUpdateAllowTransitiveDependencies(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getUpdateAllowTransitiveDependencies');
    }

    public function getUpdateAllowTransitiveRootDependencies(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getUpdateAllowTransitiveRootDependencies');
    }

    public function getRequires(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRequires');
    }

    public function getFixedPackages(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getFixedPackages');
    }

    public function isFixedPackage(BasePackage $package): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isFixedPackage');
    }

    public function getLockedPackages(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getLockedPackages');
    }

    public function isLockedPackage(PackageInterface $package): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isLockedPackage');
    }

    public function getFixedOrLockedPackages(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getFixedOrLockedPackages');
    }

    public function getPresentMap(bool $packageIds = false): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPresentMap');
    }

    public function getFixedPackagesMap(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getFixedPackagesMap');
    }

    public function getLockedRepository(): ?LockArrayRepository
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getLockedRepository');
    }

    public function restrictPackages(array $names): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'restrictPackages');
    }

    public function getRestrictedPackages(): ?array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRestrictedPackages');
    }
}
