<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\DependencyResolver\RuleSet.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\DependencyResolver;

use Composer\Repository\RepositorySet;

class RuleSet implements \IteratorAggregate, \Countable
{
    public const TYPE_PACKAGE = 0;
    public const TYPE_REQUEST = 1;
    public const TYPE_LEARNED = 4;
    public const TYPES = [
        self::TYPE_PACKAGE => 'PACKAGE',
        self::TYPE_REQUEST => 'REQUEST',
        self::TYPE_LEARNED => 'LEARNED',
    ];

    public function __construct()
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function add(Rule $rule, $type): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'add');
    }

    public function count(): int
    {
        \ShirabeUnsupportedClass::fail(self::class, 'count');
    }

    public function ruleById(int $id): Rule
    {
        \ShirabeUnsupportedClass::fail(self::class, 'ruleById');
    }

    public function getRules(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRules');
    }

    public function getIterator(): RuleSetIterator
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getIterator');
    }

    public function getIteratorFor($types): RuleSetIterator
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getIteratorFor');
    }

    public function getIteratorWithout($types): RuleSetIterator
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getIteratorWithout');
    }

    public function getTypes(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getTypes');
    }

    public function getPrettyString(?RepositorySet $repositorySet = null, ?Request $request = null, ?Pool $pool = null, bool $isVerbose = false): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPrettyString');
    }

    public function __toString(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, '__toString');
    }
}
