<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\DependencyResolver\RuleSetIterator.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\DependencyResolver;

class RuleSetIterator implements \Iterator
{
    public function __construct(array $rules)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function current(): Rule
    {
        \ShirabeUnsupportedClass::fail(self::class, 'current');
    }

    public function key(): int
    {
        \ShirabeUnsupportedClass::fail(self::class, 'key');
    }

    public function next(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'next');
    }

    public function rewind(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'rewind');
    }

    public function valid(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'valid');
    }
}
