<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\DependencyResolver\RuleSetGenerator.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\DependencyResolver;

use Composer\Filter\PlatformRequirementFilter\PlatformRequirementFilterInterface;
use Composer\Package\BasePackage;

class RuleSetGenerator
{
    public function __construct(PolicyInterface $policy, Pool $pool)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    protected function createRequireRule(BasePackage $package, array $providers, $reason, $reasonData): ?Rule
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createRequireRule');
    }

    protected function createInstallOneOfRule(array $packages, $reason, $reasonData): Rule
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createInstallOneOfRule');
    }

    protected function createRule2Literals(BasePackage $issuer, BasePackage $provider, $reason, $reasonData): ?Rule
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createRule2Literals');
    }

    protected function createMultiConflictRule(array $packages, $reason, $reasonData): Rule
    {
        \ShirabeUnsupportedClass::fail(self::class, 'createMultiConflictRule');
    }

    protected function addRulesForPackage(BasePackage $package, PlatformRequirementFilterInterface $platformRequirementFilter): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'addRulesForPackage');
    }

    protected function addConflictRules(PlatformRequirementFilterInterface $platformRequirementFilter): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'addConflictRules');
    }

    protected function addRulesForRequest(Request $request, PlatformRequirementFilterInterface $platformRequirementFilter): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'addRulesForRequest');
    }

    protected function addRulesForRootAliases(PlatformRequirementFilterInterface $platformRequirementFilter): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'addRulesForRootAliases');
    }

    public function getRulesFor(Request $request, ?PlatformRequirementFilterInterface $platformRequirementFilter = null): RuleSet
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRulesFor');
    }
}
