<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\DependencyResolver\SecurityAdvisoryPoolFilter.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\DependencyResolver;

use Composer\Advisory\AuditConfig;
use Composer\Advisory\Auditor;

class SecurityAdvisoryPoolFilter
{
    public function __construct(Auditor $auditor, AuditConfig $auditConfig)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function filter(Pool $pool, array $repositories, Request $request): Pool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'filter');
    }
}
