<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\DependencyResolver\Solver.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\DependencyResolver;

use Composer\Filter\PlatformRequirementFilter\PlatformRequirementFilterInterface;
use Composer\IO\IOInterface;

class Solver
{
    private const BRANCH_LITERALS = 0;
    private const BRANCH_LEVEL = 1;

    public function __construct(PolicyInterface $policy, Pool $pool, IOInterface $io)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getRuleSetSize(): int
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRuleSetSize');
    }

    public function getPool(): Pool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPool');
    }

    protected function setupFixedMap(Request $request): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setupFixedMap');
    }

    protected function checkForRootRequireProblems(Request $request, PlatformRequirementFilterInterface $platformRequirementFilter): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'checkForRootRequireProblems');
    }

    public function solve(Request $request, ?PlatformRequirementFilterInterface $platformRequirementFilter = null): LockTransaction
    {
        \ShirabeUnsupportedClass::fail(self::class, 'solve');
    }

    protected function propagate(int $level): ?Rule
    {
        \ShirabeUnsupportedClass::fail(self::class, 'propagate');
    }

    protected function analyze(int $level, Rule $rule): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'analyze');
    }
}
