<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\DependencyResolver\Transaction.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\DependencyResolver;

use Composer\Package\Link;

class Transaction
{
    public function __construct(array $presentPackages, array $resultPackages)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getOperations(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getOperations');
    }

    protected function calculateOperations(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'calculateOperations');
    }

    protected function getRootPackages(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRootPackages');
    }

    protected function getProvidersInResult(Link $link): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getProvidersInResult');
    }
}
