<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Proxy stub for Composer\Package\AliasPackage: the public surface forwards to the Rust-side entity over RPC.

namespace Composer\Package;

class AliasPackage extends BasePackage
{
    public function __construct(BasePackage $aliasOf, string $version, string $prettyVersion)
    {
        [$this->__rhandle, $this->__epoch] = \ShirabeRpcRuntime::callRust(0, '__shirabeConstruct', [static::class, [$aliasOf, $version, $prettyVersion]]);
        \ShirabeRustObjectRegistry::adopt($this->__rhandle, $this);
    }

    public function getAliasOf()
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getAliasOf', []);
    }

    public function setRootPackageAlias(bool $value): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setRootPackageAlias', [$value]);
    }

    public function isRootPackageAlias(): bool
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'isRootPackageAlias', []);
    }

    public function hasSelfVersionRequires(): bool
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'hasSelfVersionRequires', []);
    }
}
