<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Proxy stub for Composer\Package\CompletePackage: the public surface forwards to the Rust-side entity over RPC.

namespace Composer\Package;

class CompletePackage extends Package implements CompletePackageInterface
{
    public function getScripts(): array
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getScripts', []);
    }

    public function setScripts(array $scripts): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setScripts', [$scripts]);
    }

    public function getRepositories(): array
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getRepositories', []);
    }

    public function setRepositories(array $repositories): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setRepositories', [$repositories]);
    }

    public function getLicense(): array
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getLicense', []);
    }

    public function setLicense(array $license): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setLicense', [$license]);
    }

    public function getKeywords(): array
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getKeywords', []);
    }

    public function setKeywords(array $keywords): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setKeywords', [$keywords]);
    }

    public function getDescription(): ?string
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getDescription', []);
    }

    public function setDescription(?string $description): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setDescription', [$description]);
    }

    public function getHomepage(): ?string
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getHomepage', []);
    }

    public function setHomepage(?string $homepage): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setHomepage', [$homepage]);
    }

    public function getAuthors(): array
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getAuthors', []);
    }

    public function setAuthors(array $authors): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setAuthors', [$authors]);
    }

    public function getSupport(): array
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getSupport', []);
    }

    public function setSupport(array $support): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setSupport', [$support]);
    }

    public function getFunding(): array
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getFunding', []);
    }

    public function setFunding(array $funding): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setFunding', [$funding]);
    }

    public function isAbandoned(): bool
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'isAbandoned', []);
    }

    public function getReplacementPackage(): ?string
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getReplacementPackage', []);
    }

    public function setAbandoned($abandoned): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setAbandoned', [$abandoned]);
    }

    public function getArchiveName(): ?string
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getArchiveName', []);
    }

    public function setArchiveName(?string $name): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setArchiveName', [$name]);
    }

    public function getArchiveExcludes(): array
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getArchiveExcludes', []);
    }

    public function setArchiveExcludes(array $excludes): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setArchiveExcludes', [$excludes]);
    }
}
