<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Proxy stub for Composer\Package\Package: the public surface forwards to the Rust-side entity over RPC.

namespace Composer\Package;

class Package extends BasePackage
{
    public function setType(string $type): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setType', [$type]);
    }

    public function setTargetDir(?string $targetDir): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setTargetDir', [$targetDir]);
    }

    public function setExtra(array $extra): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setExtra', [$extra]);
    }

    public function setBinaries(array $binaries): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setBinaries', [$binaries]);
    }

    public function setSourceType(?string $type): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setSourceType', [$type]);
    }

    public function setSourceUrl(?string $url): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setSourceUrl', [$url]);
    }

    public function setDistSha1Checksum(?string $sha1checksum): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setDistSha1Checksum', [$sha1checksum]);
    }

    public function setReleaseDate(?\DateTimeInterface $releaseDate): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setReleaseDate', [$releaseDate]);
    }

    public function setRequires(array $requires): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setRequires', [$requires]);
    }

    public function setConflicts(array $conflicts): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setConflicts', [$conflicts]);
    }

    public function setProvides(array $provides): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setProvides', [$provides]);
    }

    public function setReplaces(array $replaces): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setReplaces', [$replaces]);
    }

    public function setDevRequires(array $devRequires): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setDevRequires', [$devRequires]);
    }

    public function setSuggests(array $suggests): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setSuggests', [$suggests]);
    }

    public function setAutoload(array $autoload): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setAutoload', [$autoload]);
    }

    public function setDevAutoload(array $devAutoload): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setDevAutoload', [$devAutoload]);
    }

    public function setIncludePaths(array $includePaths): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setIncludePaths', [$includePaths]);
    }

    public function setPhpExt(?array $phpExt): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setPhpExt', [$phpExt]);
    }

    public function setNotificationUrl(string $notificationUrl): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setNotificationUrl', [$notificationUrl]);
    }

    public function setIsDefaultBranch(bool $defaultBranch): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setIsDefaultBranch', [$defaultBranch]);
    }

    public function replaceVersion(string $version, string $prettyVersion): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'replaceVersion', [$version, $prettyVersion]);
    }
}
