<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Proxy stub for Composer\Package\RootPackage: the public surface forwards to the Rust-side entity over RPC.

namespace Composer\Package;

class RootPackage extends CompletePackage implements RootPackageInterface
{
    public const DEFAULT_PRETTY_VERSION = '1.0.0+no-version-set';

    public function getAliases(): array
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getAliases', []);
    }

    public function getMinimumStability(): string
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getMinimumStability', []);
    }

    public function getStabilityFlags(): array
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getStabilityFlags', []);
    }

    public function getReferences(): array
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getReferences', []);
    }

    public function getPreferStable(): bool
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getPreferStable', []);
    }

    public function getConfig(): array
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getConfig', []);
    }

    public function setStabilityFlags(array $stabilityFlags): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setStabilityFlags', [$stabilityFlags]);
    }

    public function setMinimumStability(string $minimumStability): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setMinimumStability', [$minimumStability]);
    }

    public function setPreferStable(bool $preferStable): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setPreferStable', [$preferStable]);
    }

    public function setConfig(array $config): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setConfig', [$config]);
    }

    public function setReferences(array $references): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setReferences', [$references]);
    }

    public function setAliases(array $aliases): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setAliases', [$aliases]);
    }
}
