<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Proxy stub for Composer\Package\RootAliasPackage: the public surface forwards to the Rust-side entity over RPC.

namespace Composer\Package;

class RootAliasPackage extends CompleteAliasPackage implements RootPackageInterface
{
    public function __construct(RootPackage $aliasOf, string $version, string $prettyVersion)
    {
        [$this->__rhandle, $this->__epoch] = \ShirabeRpcRuntime::callRust(0, '__shirabeConstruct', [static::class, [$aliasOf, $version, $prettyVersion]]);
        \ShirabeRustObjectRegistry::adopt($this->__rhandle, $this);
    }

    public function getAliases(): array
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getAliases', []);
    }

    public function getMinimumStability(): string
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getMinimumStability', []);
    }

    public function getStabilityFlags(): array
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getStabilityFlags', []);
    }

    public function getReferences(): array
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getReferences', []);
    }

    public function getPreferStable(): bool
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getPreferStable', []);
    }

    public function getConfig(): array
    {
        return \ShirabeRpcRuntime::callRust($this->__rhandle, 'getConfig', []);
    }

    public function setRequires(array $requires): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setRequires', [$requires]);
    }

    public function setDevRequires(array $devRequires): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setDevRequires', [$devRequires]);
    }

    public function setConflicts(array $conflicts): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setConflicts', [$conflicts]);
    }

    public function setProvides(array $provides): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setProvides', [$provides]);
    }

    public function setReplaces(array $replaces): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setReplaces', [$replaces]);
    }

    public function setAutoload(array $autoload): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setAutoload', [$autoload]);
    }

    public function setDevAutoload(array $devAutoload): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setDevAutoload', [$devAutoload]);
    }

    public function setStabilityFlags(array $stabilityFlags): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setStabilityFlags', [$stabilityFlags]);
    }

    public function setMinimumStability(string $minimumStability): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setMinimumStability', [$minimumStability]);
    }

    public function setPreferStable(bool $preferStable): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setPreferStable', [$preferStable]);
    }

    public function setConfig(array $config): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setConfig', [$config]);
    }

    public function setReferences(array $references): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setReferences', [$references]);
    }

    public function setAliases(array $aliases): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setAliases', [$aliases]);
    }

    public function setSuggests(array $suggests): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setSuggests', [$suggests]);
    }

    public function setExtra(array $extra): void
    {
        \ShirabeRpcRuntime::callRust($this->__rhandle, 'setExtra', [$extra]);
    }
}
