[package]
name = "shirabe-external-packages"
version.workspace = true
edition.workspace = true

[dependencies]
shirabe-pcre.workspace = true
shirabe-php-shim.workspace = true
shirabe-semver.workspace = true
shirabe-symfony-string.workspace = true
anyhow.workspace = true
chrono.workspace = true
indexmap.workspace = true
regex.workspace = true

[lints]
workspace = true
