<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Advisory\AuditConfig.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Advisory;

use Composer\Config;

class AuditConfig
{
    public function __construct(bool $audit, string $auditFormat, string $auditAbandoned, bool $blockInsecure, bool $blockAbandoned, bool $ignoreUnreachable, array $ignoreListForAudit, array $ignoreListForBlocking, array $ignoreSeverityForAudit, array $ignoreSeverityForBlocking, array $ignoreAbandonedForAudit, array $ignoreAbandonedForBlocking)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public static function fromConfig(Config $config, bool $audit = true, string $auditFormat = Auditor::FORMAT_SUMMARY): self
    {
        \ShirabeUnsupportedClass::fail(self::class, 'fromConfig');
    }
}
