<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Advisory\PartialSecurityAdvisory.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Advisory;

use Composer\Semver\Constraint\ConstraintInterface;
use Composer\Semver\VersionParser;
use JsonSerializable;

class PartialSecurityAdvisory implements JsonSerializable
{
    public static function create(string $packageName, array $data, VersionParser $parser): self
    {
        \ShirabeUnsupportedClass::fail(self::class, 'create');
    }

    public function __construct(string $packageName, string $advisoryId, ConstraintInterface $affectedVersions)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function jsonSerialize()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'jsonSerialize');
    }
}
