<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Advisory\SecurityAdvisory.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Advisory;

use Composer\Semver\Constraint\ConstraintInterface;
use DateTimeImmutable;

class SecurityAdvisory extends PartialSecurityAdvisory
{
    public function __construct(string $packageName, string $advisoryId, ConstraintInterface $affectedVersions, string $title, array $sources, DateTimeImmutable $reportedAt, ?string $cve = null, ?string $link = null, ?string $severity = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function toIgnoredAdvisory(?string $ignoreReason): IgnoredSecurityAdvisory
    {
        \ShirabeUnsupportedClass::fail(self::class, 'toIgnoredAdvisory');
    }

    public function jsonSerialize()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'jsonSerialize');
    }
}
