<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Util\AuthHelper.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Util;

use Composer\Config;
use Composer\IO\IOInterface;

class AuthHelper
{
    public function __construct(IOInterface $io, Config $config)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function storeAuth(string $origin, $storeAuth): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'storeAuth');
    }

    public function promptAuthIfNeeded(string $url, string $origin, int $statusCode, ?string $reason = null, array $headers = [], int $retryCount = 0, ?string $responseBody = null): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'promptAuthIfNeeded');
    }

    public function addAuthenticationHeader(array $headers, string $origin, string $url): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'addAuthenticationHeader');
    }

    public function addAuthenticationOptions(array $options, string $origin, string $url): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'addAuthenticationOptions');
    }

    public function isPublicBitBucketDownload(string $urlToBitBucketFile): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isPublicBitBucketDownload');
    }
}
