<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Util\Bitbucket.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Util;

use Composer\IO\IOInterface;
use Composer\Config;

class Bitbucket
{
    public const OAUTH2_ACCESS_TOKEN_URL = 'https://bitbucket.org/site/oauth2/access_token';

    public function __construct(IOInterface $io, Config $config, ?ProcessExecutor $process = null, ?HttpDownloader $httpDownloader = null, ?int $time = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getToken(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getToken');
    }

    public function authorizeOAuth(string $originUrl): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'authorizeOAuth');
    }

    public function authorizeOAuthInteractively(string $originUrl, ?string $message = null): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'authorizeOAuthInteractively');
    }

    public function requestToken(string $originUrl, string $consumerKey, string $consumerSecret): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'requestToken');
    }
}
