<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Util\ConfigValidator.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Util;

use Composer\Package\Loader\ValidatingArrayLoader;
use Composer\IO\IOInterface;

class ConfigValidator
{
    public const CHECK_VERSION = 1;

    public function __construct(IOInterface $io)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function validate(string $file, int $arrayLoaderValidationFlags = ValidatingArrayLoader::CHECK_ALL, int $flags = self::CHECK_VERSION): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'validate');
    }
}
