<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Util\GitHub.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Util;

use Composer\IO\IOInterface;
use Composer\Config;

class GitHub
{
    public const GITHUB_TOKEN_REGEX = '{^([a-f0-9]{12,}|gh[a-z]_[a-zA-Z0-9_]+|github_pat_[a-zA-Z0-9_]+)$}';

    public function __construct(IOInterface $io, Config $config, ?ProcessExecutor $process = null, ?HttpDownloader $httpDownloader = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function authorizeOAuth(string $originUrl): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'authorizeOAuth');
    }

    public function authorizeOAuthInteractively(string $originUrl, ?string $message = null): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'authorizeOAuthInteractively');
    }

    public function getRateLimit(array $headers): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRateLimit');
    }

    public function getSsoUrl(array $headers): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getSsoUrl');
    }

    public function isRateLimited(array $headers): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isRateLimited');
    }

    public function requiresSso(array $headers): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'requiresSso');
    }
}
