<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Util\GitLab.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Util;

use Composer\IO\IOInterface;
use Composer\Config;

class GitLab
{
    public function __construct(IOInterface $io, Config $config, ?ProcessExecutor $process = null, ?HttpDownloader $httpDownloader = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function authorizeOAuth(string $originUrl): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'authorizeOAuth');
    }

    public function authorizeOAuthInteractively(string $scheme, string $originUrl, ?string $message = null): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'authorizeOAuthInteractively');
    }

    public function authorizeOAuthRefresh(string $scheme, string $originUrl): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'authorizeOAuthRefresh');
    }

    public function isOAuthExpired(string $originUrl): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isOAuthExpired');
    }
}
