<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Util\HttpDownloader.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Util;

use Composer\Config;
use Composer\IO\IOInterface;

class HttpDownloader
{
    private const STATUS_QUEUED = 1;
    private const STATUS_STARTED = 2;
    private const STATUS_COMPLETED = 3;
    private const STATUS_FAILED = 4;
    private const STATUS_ABORTED = 5;

    public function __construct(IOInterface $io, Config $config, array $options = [], bool $disableTls = false)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function get(string $url, array $options = [])
    {
        \ShirabeUnsupportedClass::fail(self::class, 'get');
    }

    public function add(string $url, array $options = [])
    {
        \ShirabeUnsupportedClass::fail(self::class, 'add');
    }

    public function copy(string $url, string $to, array $options = [])
    {
        \ShirabeUnsupportedClass::fail(self::class, 'copy');
    }

    public function addCopy(string $url, string $to, array $options = [])
    {
        \ShirabeUnsupportedClass::fail(self::class, 'addCopy');
    }

    public function getOptions()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getOptions');
    }

    public function setOptions(array $options)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setOptions');
    }

    public function wait(?int $index = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'wait');
    }

    public function enableAsync(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'enableAsync');
    }

    public function countActiveJobs(?int $index = null): int
    {
        \ShirabeUnsupportedClass::fail(self::class, 'countActiveJobs');
    }

    public static function outputWarnings(IOInterface $io, string $url, $data): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'outputWarnings');
    }

    public static function getExceptionHints(\Throwable $e): ?array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getExceptionHints');
    }

    public static function isCurlEnabled(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isCurlEnabled');
    }
}
