<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Util\Loop.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Util;

use Symfony\Component\Console\Helper\ProgressBar;

class Loop
{
    public function __construct(HttpDownloader $httpDownloader, ?ProcessExecutor $processExecutor = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function getHttpDownloader(): HttpDownloader
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getHttpDownloader');
    }

    public function getProcessExecutor(): ?ProcessExecutor
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getProcessExecutor');
    }

    public function wait(array $promises, ?ProgressBar $progress = null): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'wait');
    }

    public function abortJobs(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'abortJobs');
    }
}
