<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Util\Perforce.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Util;

use Composer\IO\IOInterface;

class Perforce
{
    public function __construct($repoConfig, string $port, string $path, ProcessExecutor $process, bool $isWindows, IOInterface $io)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public static function create($repoConfig, string $port, string $path, ProcessExecutor $process, IOInterface $io): self
    {
        \ShirabeUnsupportedClass::fail(self::class, 'create');
    }

    public static function checkServerExists(string $url, ProcessExecutor $processExecutor): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'checkServerExists');
    }

    public function initialize($repoConfig): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'initialize');
    }

    public function initializeDepotAndBranch(?string $depot, ?string $branch): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'initializeDepotAndBranch');
    }

    public function generateUniquePerforceClientName(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'generateUniquePerforceClientName');
    }

    public function cleanupClientSpec(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'cleanupClientSpec');
    }

    protected function executeCommand($command): int
    {
        \ShirabeUnsupportedClass::fail(self::class, 'executeCommand');
    }

    public function getClient(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getClient');
    }

    protected function getPath(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPath');
    }

    public function initializePath(string $path): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'initializePath');
    }

    protected function getPort(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPort');
    }

    public function setStream(string $stream): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setStream');
    }

    public function isStream(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isStream');
    }

    public function getStream(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getStream');
    }

    public function getStreamWithoutLabel(string $stream): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getStreamWithoutLabel');
    }

    public function getP4ClientSpec(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getP4ClientSpec');
    }

    public function getUser(): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getUser');
    }

    public function setUser(?string $user): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setUser');
    }

    public function queryP4User(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'queryP4User');
    }

    protected function getP4variable(string $name): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getP4variable');
    }

    public function queryP4Password(): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'queryP4Password');
    }

    public function generateP4Command(array $arguments, bool $useClient = true): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'generateP4Command');
    }

    public function isLoggedIn(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isLoggedIn');
    }

    public function connectClient(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'connectClient');
    }

    public function syncCodeBase(?string $sourceReference): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'syncCodeBase');
    }

    public function writeClientSpecToFile($spec): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'writeClientSpecToFile');
    }

    public function writeP4ClientSpec(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'writeP4ClientSpec');
    }

    protected function read($pipe, $name): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'read');
    }

    public function windowsLogin(?string $password): int
    {
        \ShirabeUnsupportedClass::fail(self::class, 'windowsLogin');
    }

    public function p4Login(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'p4Login');
    }

    public function getComposerInformation(string $identifier): ?array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getComposerInformation');
    }

    public function getFileContent(string $file, string $identifier): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getFileContent');
    }

    public function getFilePath(string $file, string $identifier): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getFilePath');
    }

    public function getBranches(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getBranches');
    }

    public function getTags(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getTags');
    }

    public function checkStream(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'checkStream');
    }

    protected function getChangeList(string $reference): mixed
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getChangeList');
    }

    public function getCommitLogs(string $fromReference, string $toReference): mixed
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getCommitLogs');
    }

    public function getFilesystem(): Filesystem
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getFilesystem');
    }

    public function setFilesystem(Filesystem $fs): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setFilesystem');
    }
}
