<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Util\Platform.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Util;

class Platform
{
    public function __construct()
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public static function getCwd(bool $allowEmpty = false): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getCwd');
    }

    public static function realpath(string $path): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'realpath');
    }

    public static function getEnv(string $name)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getEnv');
    }

    public static function putEnv(string $name, string $value): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'putEnv');
    }

    public static function clearEnv(string $name): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'clearEnv');
    }

    public static function expandPath(string $path): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'expandPath');
    }

    public static function getUserDirectory(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getUserDirectory');
    }

    public static function isWindowsSubsystemForLinux(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isWindowsSubsystemForLinux');
    }

    public static function isWindows(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isWindows');
    }

    public static function isDocker(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isDocker');
    }

    public static function strlen(string $str): int
    {
        \ShirabeUnsupportedClass::fail(self::class, 'strlen');
    }

    public static function isTty($fd = null): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isTty');
    }

    public static function isInputCompletionProcess(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isInputCompletionProcess');
    }

    public static function workaroundFilesystemIssues(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'workaroundFilesystemIssues');
    }

    public static function getDevNull(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getDevNull');
    }
}
