<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Util\ProcessExecutor.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Util;

use Composer\IO\IOInterface;
use React\Promise\PromiseInterface;

class ProcessExecutor
{
    private const STATUS_QUEUED = 1;
    private const STATUS_STARTED = 2;
    private const STATUS_COMPLETED = 3;
    private const STATUS_FAILED = 4;
    private const STATUS_ABORTED = 5;
    private const BUILTIN_CMD_COMMANDS = [
        'assoc', 'break', 'call', 'cd', 'chdir', 'cls', 'color', 'copy', 'date',
        'del', 'dir', 'echo', 'endlocal', 'erase', 'exit', 'for', 'ftype', 'goto',
        'help', 'if', 'label', 'md', 'mkdir', 'mklink', 'move', 'path', 'pause',
        'popd', 'prompt', 'pushd', 'rd', 'rem', 'ren', 'rename', 'rmdir', 'set',
        'setlocal', 'shift', 'start', 'time', 'title', 'type', 'ver', 'vol',
    ];
    private const GIT_CMDS_NEED_GIT_DIR = [
        ['show'],
        ['log'],
        ['branch'],
        ['remote', 'set-url'],
    ];

    public function __construct(?IOInterface $io = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function execute($command, &$output = null, ?string $cwd = null): int
    {
        \ShirabeUnsupportedClass::fail(self::class, 'execute');
    }

    public function executeTty($command, ?string $cwd = null): int
    {
        \ShirabeUnsupportedClass::fail(self::class, 'executeTty');
    }

    public function executeAsync($command, ?string $cwd = null): PromiseInterface
    {
        \ShirabeUnsupportedClass::fail(self::class, 'executeAsync');
    }

    protected function outputHandler(string $type, string $buffer): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'outputHandler');
    }

    public function setMaxJobs(int $maxJobs): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setMaxJobs');
    }

    public function resetMaxJobs(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'resetMaxJobs');
    }

    public function wait($index = null): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'wait');
    }

    public function enableAsync(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'enableAsync');
    }

    public function countActiveJobs($index = null): int
    {
        \ShirabeUnsupportedClass::fail(self::class, 'countActiveJobs');
    }

    public function splitLines(?string $output): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'splitLines');
    }

    public function getErrorOutput(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getErrorOutput');
    }

    public static function getTimeout(): int
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getTimeout');
    }

    public static function setTimeout(int $timeout): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setTimeout');
    }

    public static function escape($argument): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'escape');
    }

    public function requiresGitDirEnv($command): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'requiresGitDirEnv');
    }
}
