<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Util\RemoteFilesystem.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Util;

use Composer\Config;
use Composer\IO\IOInterface;

class RemoteFilesystem
{
    public function __construct(IOInterface $io, Config $config, array $options = [], bool $disableTls = false, ?AuthHelper $authHelper = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public function copy(string $originUrl, string $fileUrl, string $fileName, bool $progress = true, array $options = [])
    {
        \ShirabeUnsupportedClass::fail(self::class, 'copy');
    }

    public function getContents(string $originUrl, string $fileUrl, bool $progress = true, array $options = [])
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getContents');
    }

    public function getOptions()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getOptions');
    }

    public function setOptions(array $options)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setOptions');
    }

    public function isTlsDisabled()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'isTlsDisabled');
    }

    public function getLastHeaders()
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getLastHeaders');
    }

    public static function findStatusCode(array $headers)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'findStatusCode');
    }

    public function findStatusMessage(array $headers)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'findStatusMessage');
    }

    protected function get(string $originUrl, string $fileUrl, array $additionalOptions = [], ?string $fileName = null, bool $progress = true)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'get');
    }

    protected function getRemoteContents(string $originUrl, string $fileUrl, $context, ?array &$responseHeaders = null, ?int $maxFileSize = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getRemoteContents');
    }

    protected function callbackGet(int $notificationCode, int $severity, ?string $message, int $messageCode, int $bytesTransferred, int $bytesMax)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'callbackGet');
    }

    protected function promptAuthAndRetry($httpStatus, ?string $reason = null, array $headers = [])
    {
        \ShirabeUnsupportedClass::fail(self::class, 'promptAuthAndRetry');
    }

    protected function getOptionsForUrl(string $originUrl, array $additionalOptions)
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getOptionsForUrl');
    }
}
