<?php

// Generated by scripts/plugin-stub-generator; do not edit by hand.
// Guard for Composer\Util\Svn.
// The Rust side owns this class and the worker has no proxy for it, so this
// declaration shadows the real one: the constants and the hierarchy stay, while
// constructing it or calling anything on it raises an explicit error.

namespace Composer\Util;

use Composer\Config;
use Composer\IO\IOInterface;

class Svn
{
    private const MAX_QTY_AUTH_TRIES = 5;

    public function __construct(string $url, IOInterface $io, Config $config, ?ProcessExecutor $process = null)
    {
        \ShirabeUnsupportedClass::fail(self::class, '__construct');
    }

    public static function cleanEnv(): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'cleanEnv');
    }

    public function execute(array $command, string $url, ?string $cwd = null, ?string $path = null, bool $verbose = false): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'execute');
    }

    public function executeLocal(array $command, string $path, ?string $cwd = null, bool $verbose = false): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'executeLocal');
    }

    public function setCacheCredentials(bool $cacheCredentials): void
    {
        \ShirabeUnsupportedClass::fail(self::class, 'setCacheCredentials');
    }

    protected function doAuthDance(): Svn
    {
        \ShirabeUnsupportedClass::fail(self::class, 'doAuthDance');
    }

    protected function getCommand(array $cmd, string $url, ?string $path = null): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getCommand');
    }

    protected function getCredentialArgs(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getCredentialArgs');
    }

    protected function getPassword(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getPassword');
    }

    protected function getUsername(): string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getUsername');
    }

    protected function hasAuth(): bool
    {
        \ShirabeUnsupportedClass::fail(self::class, 'hasAuth');
    }

    protected function getAuthCacheArgs(): array
    {
        \ShirabeUnsupportedClass::fail(self::class, 'getAuthCacheArgs');
    }

    public function binaryVersion(): ?string
    {
        \ShirabeUnsupportedClass::fail(self::class, 'binaryVersion');
    }
}
